#pragma once


#ifdef _MXPARAMDLL
#define  MXPARAMDLL __declspec( dllexport )
#else
#define  MXPARAMDLL __declspec( dllimport )
#endif

#include "waxsys.h"
#include "Textdata.h"

//Die Tabellenspalten in der Stammdatenbank müssen mit diesen Bezeichnungen übereinsteimmen
#define LANGUAGE_DEUTSCH "Deutsch"
#define LANGUAGE_ENGLISCH "Englisch"

#define LANGUAGE WaxSys::LANGUAGE
#define EMPFAENGER WaxSys::EMPFAENGER
#define DISPLAYNAME WaxSys::DISPLAYNAME
#define BETREFF WaxSys::BETREFF
#define TRENNZEICHEN WaxSys::TRENNZEICHEN
#define VIEWERVORSCHAU WaxSys::VIEWERVORSCHAU
#define VIEWERDRUCK WaxSys::VIEWERDRUCK
#define LIEFERFRIST WaxSys::LIEFERFRIST
#define EXCEL WaxSys::EXCEL
#define PROJEKTE WaxSys::PROJEKTE
#define KOMP WaxSys::KOMP
#define AUTOSAVE WaxSys::AUTOSAVE
#define BAUMFARBE WaxSys::BAUMFARBE
#define GRAPHIKFENSTER WaxSys::GRAPHIKFENSTER
#define SHOWFREIGABEPOS WaxSys::SHOWFREIGABEPOS
#define ICONGROESSE WaxSys::ICONGROESSE
#define SYMBOLLEISTE WaxSys::SYMBOLLEISTE 
#define STATUSZEILE WaxSys::STATUSZEILE 
#define ZMASSLISTE WaxSys::ZMASSLISTE
#define ZMASSGRAPHIK WaxSys::ZMASSGRAPHIK
#define TEXTFORMAT WaxSys::TEXTFORMAT
#define DN2ZOLL WaxSys::DN2ZOLL
#define WINKELAUSRICHTUNG WaxSys::WINKELAUSRICHTUNG
#define FONTGROESSE WaxSys::FONTGROESSE
#define BEMASSUNGSLINIE WaxSys::BEMASSUNGSLINIE
#define TRENNLINIE WaxSys::TRENNLINIE
#define RAHMEN WaxSys::RAHMEN
#define BESCHRIFTUNGLAENGE WaxSys::BESCHRIFTUNGLAENGE
#define AUTOFREIGABE WaxSys::AUTOFREIGABE
#define SAFEFREIGABE WaxSys::SAFEFREIGABE
#define CHECKSTATUS WaxSys::CHECKSTATUS
#define CHECKSAP WaxSys::CHECKSAP
#define STAMMDB WaxSys::STAMMDB
#define SAPSOAPSERVER WaxSys::SAPSOAPSERVER
#define SERVERDB WaxSys::SERVERDB
#define MAXPOSPERSA WaxSys::MAXPOSPERSA
#define AV WaxSys::AV
#define IB_NL_KENNUNG WaxSys::IB_NL_KENNUNG
#define DEBUGNL WaxSys::DEBUGNL
#define BEARBEITER WaxSys::BEARBEITER
#define GF_DN2ZOLL WaxSys::GF_DN2ZOLL
#define GF_DWFHOEHE WaxSys::GF_DWFHOEHE
#define REL_ABST_AENDERN WaxSys::REL_ABST_AENDERN
#define MBTERMIN WaxSys::MBTERMIN
#define DIR_GROHR_FREE WaxSys::DIR_GROHR_FREE
#define DIR_GROHR_ACTIVE WaxSys::DIR_GROHR_ACTIVE
#define DIR_GROHR_STOPPED WaxSys::DIR_GROHR_STOPPED
#define DIR_GROHR_FINISHED WaxSys::DIR_GROHR_FINISHED
#define DIR_GROHR_ARCHIVE WaxSys::DIR_GROHR_ARCHIVE
#define DIR_SAEGENUT_FREE WaxSys::DIR_SAEGENUT_FREE
#define DIR_SAEGENUT_ACTIVE WaxSys::DIR_SAEGENUT_ACTIVE
#define DIR_SAEGENUT_STOPPED WaxSys::DIR_SAEGENUT_STOPPED
#define DIR_SAEGENUT_FINISHED WaxSys::DIR_SAEGENUT_FINISHED
#define DIR_SAEGENUT_ARCHIVE WaxSys::DIR_SAEGENUT_ARCHIVE
#define DIR_VERTEILER_FREE WaxSys::DIR_VERTEILER_FREE
#define DIR_VERTEILER_FREE_USB  WaxSys::DIR_VERTEILER_FREE_USB
#define DIR_VERTEILER1_ACTIVE WaxSys::DIR_VERTEILER1_ACTIVE
#define DIR_VERTEILER1_STOPPED WaxSys::DIR_VERTEILER1_STOPPED
#define DIR_VERTEILER1_FINISHED WaxSys::DIR_VERTEILER1_FINISHED
#define DIR_VERTEILER2_ACTIVE WaxSys::DIR_VERTEILER2_ACTIVE
#define DIR_VERTEILER2_STOPPED WaxSys::DIR_VERTEILER2_STOPPED
#define DIR_VERTEILER2_FINISHED WaxSys::DIR_VERTEILER2_FINISHED
#define DIR_VERTEILER_ARCHIVE WaxSys::DIR_VERTEILER_ARCHIVE
#define DIR_STRANG_FREE WaxSys::DIR_STRANG_FREE
#define DIR_STRANG1_ACTIVE WaxSys::DIR_STRANG1_ACTIVE
#define DIR_STRANG1_STOPPED WaxSys::DIR_STRANG1_STOPPED
#define DIR_STRANG1_FINISHED WaxSys::DIR_STRANG1_FINISHED
#define DIR_STRANG2_ACTIVE WaxSys::DIR_STRANG2_ACTIVE
#define DIR_STRANG2_STOPPED WaxSys::DIR_STRANG2_STOPPED
#define DIR_STRANG2_FINISHED WaxSys::DIR_STRANG2_FINISHED
#define DIR_STRANG3_ACTIVE WaxSys::DIR_STRANG3_ACTIVE
#define DIR_STRANG3_STOPPED WaxSys::DIR_STRANG3_STOPPED
#define DIR_STRANG3_FINISHED WaxSys::DIR_STRANG3_FINISHED
#define DIR_STRANG4_ACTIVE WaxSys::DIR_STRANG4_ACTIVE
#define DIR_STRANG4_STOPPED WaxSys::DIR_STRANG4_STOPPED
#define DIR_STRANG4_FINISHED WaxSys::DIR_STRANG4_FINISHED
#define DIR_STRANG_ARCHIVE WaxSys::DIR_STRANG_ARCHIVE
#define DIR_STATISTIK WaxSys::DIR_STATISTIK
#define DIR_WAXTOSAP WaxSys::DIR_WAXTOSAP
#define DIR_SAPTOWAX WaxSys::DIR_SAPTOWAX
#define DIR_SAPTOWAXWITTENBERGE WaxSys::DIR_SAPTOWAXWITTENBERGE 
#define DIR_WAXAPAX WaxSys::DIR_WAXAPAX
#define DIR_WAXAPAX_OLD WaxSys::DIR_WAXAPAX_OLD
#define DIR_WAXOLD WaxSys::DIR_WAXOLD
#define PRINT_WORD WaxSys::PRINT_WORD
#define APSAD_ROHRE WaxSys::APSAD_ROHRE
#define DIR_DOC WaxSys::DIR_DOC
#define GRAFIKFORMAT WaxSys::GRAFIKFORMAT
#define SAP_MAT_TO_WAX_EXE WaxSys::SAP_MAT_TO_WAX_EXE
#define SAP_MAT_TO_WAX_DAT WaxSys::SAP_MAT_TO_WAX_DAT



