//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by mxparam.rc
//
#define IDB_ADRESSE                     7000
#define IDB_AUSWERTUNG                  7001
#define IDB_BENUTZER                    7002
#define IDB_BROWSE                      7003
#define IDB_BUTTON_INDI                 7004
#define IDB_BUTTON_SUMME                7005
#define IDB_BUTTON_TEXT                 7006
#define IDB_BUTTON_TITEL                7007
#define IDB_CLIPBOARD_EINFUEGEN         7008
#define IDB_CLIPBOARD_KOPIEREN          7009
#define IDB_COMPUTER                    7010
#define IDB_COPY                        7011
#define IDB_CUT                         7012
#define IDB_DELETE                      7013
#define IDB_EXIT                        7014
#define IDB_FILETYPES                   7015
#define IDB_FRAGEZEICHEN                7016
#define IDB_HINWEISTEXT                 7017
#define IDB_KALKDUMMY                   7018
#define IDB_KALKULATION0                7019
#define IDB_KALKULATION1                7020
#define IDB_KALKULATION2                7021
#define IDB_KATALOG                     7022
#define IDB_LOGO1                       7023
#define IDB_LV_LAYOUT1                  7024
#define IDB_LV_LAYOUT2                  7025
#define IDB_LV_LAYOUT3                  7026
#define IDB_LV_LAYOUT4                  7027
#define IDB_PASTE                       7028
#define IDB_PROJEKT                     7029
#define IDB_PROJEKTAUFSCHLAEGE          7030
#define IDB_PROJEKTNEU                  7031
#define IDB_PROJEKTOEFFNEN              7032
#define IDB_PROJEKTVERWALTUNG           7033
#define IDB_SPANX                       7034
#define IDB_SPANXLOGO_KLEIN             7035
#define IDB_SUCHEN                      7036
#define IDB_SYSTEMPARAMS                7037
#define IDB_SYSTEMPARAMS1               7038
#define IDB_TEXTBAUSTEIN                7039
#define IDB_WIEDERVORLAGE               7040
#define idc_st                          7041
#define ID_ADRESSE                      7042
#define ID_ADRESSE_DRUCKEN              7043
#define ID_ADRESSE_EINFUEGEN            7044
#define ID_ADRESSE_LETZTERDATENSATZ     7045
#define ID_ADRESSE_LOESCHEN             7046
#define ID_ADRESSE_NEU                  7047
#define ID_ADRESSE_SPEICHERNALS         7048
#define ID_ADRESSE_SUCHEN               7049
#define ID_ALIGN                        7050
#define ID_ALLES_AUFLOESEN              7051
#define ID_ARTIKELENGLISH               7052
#define ID_ARTIKELGEANDERT              7053
#define ID_ARTIKELGELOESCHT             7054
#define ID_ARTIKELNEU                   7055
#define ID_AUFTRAGGSEROEFFNUNG          7056
#define ID_AUSWERTUNG                   7057
#define ID_BEARBEITEN                   7058
#define ID_BEARBEITUNG                  7059
#define ID_BENUTZER                     7060
#define ID_BUTTON32928                  7061
#define ID_BUTTON35111                  7062
#define ID_BUTTON40030                  7063
#define ID_BUTTON40031                  7064
#define ID_BUTTON40032                  7065
#define ID_BUTTON40033                  7066
#define ID_CHANGESTYLE                  7067
#define ID_CLIPBOARD_AUSSCHNEIDEN       7068
#define ID_CLIPBOARD_EINFUEGEN          7069
#define ID_CLIPBOARD_KOPIEREN           7070
#define ID_CONTEXTMENU_AUSSCHNEIDEN     7071
#define ID_CONTEXTMENU_BULLET           7072
#define ID_CONTEXTMENU_CENTER           7073
#define ID_CONTEXTMENU_EINFUEGEN        7074
#define ID_CONTEXTMENU_FETT             7075
#define ID_CONTEXTMENU_GROESSER         7076
#define ID_CONTEXTMENU_HOEHERSTELLEN    7077
#define ID_CONTEXTMENU_KLEINER          7078
#define ID_CONTEXTMENU_KOPIEREN         7079
#define ID_CONTEXTMENU_KURSIV           7080
#define ID_CONTEXTMENU_LEFT             7081
#define ID_CONTEXTMENU_NORMALISIEREN    7082
#define ID_CONTEXTMENU_RIGHT            7083
#define ID_CONTEXTMENU_RUECKGAENGIG     7084
#define ID_CONTEXTMENU_TIEFERSTELLEN    7085
#define ID_CONTEXTMENU_UNTERSTREICHEN   7086
#define ID_EXPORT                       7087
#define ID_FONTSELECT                   7088
#define ID_FREMDLEISTUNG                7089
#define ID_GRUPPENCODES                 7090
#define ID_GRUPPENCODES2                7091
#define ID_HINWEIS                      7092
#define ID_IMPORT                       7093
#define ID_INFO                         7094
#define ID_KOMPONENTE_NEU_KALKULATION   7095
#define ID_KOPFINFORMATIONEN_AUFTRAGSMELDUNG 7096
#define ID_KOPFINFORMATIONEN_BAUHERREN  7097
#define ID_KOPFINFORMATIONEN_PROJEKTHINWEISE 7098
#define ID_KOPFINFORMATIONEN_RANDBEDINGUNGEN 7099
#define ID_KUNDE_BEARBEITEN             7100
#define ID_KUNDE_NEU                    7101
#define ID_LAENDEREINSTELLUNGEN         7102
#define ID_LANGUAGE                     7103
#define ID_LANGUAGE_SPL                 7104
#define ID_LOESCHEN                     7105
#define ID_MAKEDOC                      7106
#define ID_MONTAGEZEITEN                7107
#define ID_MXADR                        7108
#define ID_OBJEKTEINSTELLUNGEN          7109
#define ID_ODBCADM                      7110
#define ID_OPTIONEN_SCHRIFTARTFRANZEIGE 7111
#define ID_OPTION_LV                    7112
#define ID_PASSWORT_CHANGE              7113
#define ID_POSITIONEN_NEU_INDIVIDUELL   7114
#define ID_POSITIONEN_NEU_SUMME         7115
#define ID_POSITIONEN_NEU_TEXT          7116
#define ID_POSITIONEN_NEU_TITEL         7117
#define ID_PREISLISTE                   7118
#define ID_PREISLISTE_BEARBEITEN        7119
#define ID_PREISLISTE_BLOCK_BEARBEITUNG 7120
#define ID_PREISLISTE_HINWEISTEXTE      7121
#define ID_PREISLISTE_KOPIEREN          7122
#define ID_PREISLISTE_SUCHEN            7123
#define ID_PREISLISTE_ZUSATZPREISE      7124
#define ID_PROJEKTSTATUS                7125
#define ID_RECHNUNG_IN_SAP              7126
#define ID_RUECKGAENGIG                 7127
#define ID_SEITENFORMAT                 7128
#define ID_SETFONT                      7129
#define ID_STARTWINWORD                 7130
#define ID_STATUS                       7131
#define ID_STUECKLISTE                  7132
#define ID_SUCHEN                       7133
#define ID_SYSTEMPARAMETER              7134
#define ID_TERMINSTEUERUNG              7135
#define ID_TEST                         7136
#define ID_TESTRES                      7137
#define ID_TEXTBAUSTEIN                 7138
#define ID_TEXTBAUSTEIN_AUFLOESEN       7139
#define ID_TEXTBAUSTEIN_BREITEWECHSELN  7140
#define ID_TEXTBAUSTEIN_EINFUEGEN       7141
#define ID_TEXTBAUSTEIN_LSCHEN          7142
#define ID_TEXTBAUSTEIN_SUCHEN          7143
#define ID_TRANSLATE                    7144
#define ID_TXTIMPORT                    7145
#define ID_TXTPRINT                     7146
#define ID_UMBENENNEN                   7147
#define ID_UNDELETE                     7148
#define ID_VORABANMELDUNG               7149
#define ID_WAEHRUNGSEINSTELLUNGEN       7150
#define ID_WIEDERVORLAGE                7151
#define ID_WINWORD                      7152
#define IDR_ADRESSVERWALTUNG            7153
#define IDR_AVI_FILECOPY                7154
#define LIST_SHORTCUTS                  7154
#define IDR_CLIPBOARD                   7155
#define IDR_CLIPBOARD_EXTENDED          7156
#define IDR_CONTEXTMENUARTIKEL          7157
#define IDR_CONTEXTMENUGRUPPE           7158
#define IDR_CONTEXTMENULISTE            7159
#define IDR_CONTROL                     7160
#define IDR_CONTROL_PREISLISTE          7161
#define IDR_CONTROL_PROJEKTVERWALTUNG   7162
#define IDR_LISTBOX                     7163
#define IDR_MAINFRAME                   7164
#define IDR_POPUP_ADRESSEN              7165
#define IDR_PREISLISTE                  7166
#define IDR_PROJEKTKAROVERWALTUNG       7167
#define IDR_PROJEKTKAROVERWALTUNG_SAVE  7168
#define IDR_PROJEKTVERWALTUNG           7169
#define IDR_RTFCONTROL                  7170
#define IDR_RTFTOOLBAR                  7171
#define IDR_RTF_EDIT                    7172
#define IDR_RTF_EDIT1                   7173
#define IDR_TEXTBAUSTEIN                7174
#define IDR_TREECONTROL                 7175
#define IDR_TREECONTROL_PARENT          7176
#define CG_IDC_PROGDLG_PERCENT          7177
#define CG_IDC_PROGDLG_PROGRESS         7178
#define CG_IDC_PROGDLG_STATUS           7179
#define IDC_ACTUALIZE                   7180
#define IDC_ADD                         7181
#define IDC_ADRESSEMISCHEN              7182
#define IDC_ADRESSE_ANSCHR1             7183
#define IDC_ADRESSE_ANSCHR2             7184
#define IDC_ADRESSE_ANSCHR3             7185
#define IDC_ADRESSE_ANSCHR4             7186
#define IDC_ADRESSE_ANSCHR5             7187
#define IDC_ADRESSE_ANSCHR6             7188
#define IDC_ADRESSE_AP1                 7189
#define IDC_ADRESSE_AP1ABT              7190
#define IDC_ADRESSE_AP1FAX              7191
#define IDC_ADRESSE_AP1TELEFON          7192
#define IDC_ADRESSE_AP2                 7193
#define IDC_ADRESSE_AP2ABT              7194
#define IDC_ADRESSE_AP2FAX              7195
#define IDC_ADRESSE_AP2TELEFON          7196
#define IDC_ADRESSE_AP3                 7197
#define IDC_ADRESSE_AP3ABT              7198
#define IDC_ADRESSE_AP3FAX              7199
#define IDC_ADRESSE_AP3TELEFON          7200
#define IDC_ADRESSE_CODE                7201
#define IDC_ADRESSE_DRUCKEN             7202
#define IDC_ADRESSE_ELEMENT             7203
#define IDC_ADRESSE_EMAIL               7204
#define IDC_ADRESSE_FAX                 7205
#define IDC_ADRESSE_FIRST               7206
#define IDC_ADRESSE_KNDNR               7207
#define IDC_ADRESSE_LAND                7208
#define IDC_ADRESSE_LOESCHEN            7209
#define IDC_ADRESSE_NEU                 7210
#define IDC_ADRESSE_ORT                 7211
#define IDC_ADRESSE_PLZ                 7212
#define IDC_ADRESSE_POSTFACH            7213
#define IDC_ADRESSE_RUECK               7214
#define IDC_ADRESSE_SPEICHERNALS        7215
#define IDC_ADRESSE_TELEFON             7216
#define IDC_ADRESSE_TOKEN               7217
#define IDC_ADRESSE_VOR                 7218
#define IDC_AKTUELLEZEIT                7219
#define IDC_ALLE                        7220
#define IDC_ALLEAUS                     7221
#define IDC_ALLEEIN                     7222
#define IDC_ALLEPOSI                    7223
#define IDC_ALTERNATIV                  7224
#define IDC_ALTERNATIVKENNZ             7225
#define IDC_ALTERNATIVPOSI              7226
#define IDC_ALTERNATIV_FETT             7227
#define IDC_ALTERNATIV_KURSIV           7228
#define IDC_ANGEBOT_ANZAHL              7229
#define IDC_ANGEBOT_BEARBEITEN          7230
#define IDC_ANGEBOT_GESAMTPREIS         7231
#define IDC_ANGEBOT_POSNR               7232
#define IDC_ANGEBOT_PREIS               7233
#define IDC_ANIMATE1                    7234
#define IDC_ANZAHL                      7235
#define IDC_ANZEIGE                     7236
#define IDC_AUFTRAGSBEZ                 7237
#define IDC_AUFTRAGSERTEILUNG           7238
#define IDC_AUFTRAGSMELDUNG_ERSTELLEN   7239
#define IDC_AUFTRAGSSTRUKTUR            7240
#define IDC_AUFTRAGSTYP                 7241
#define IDC_AUS_LISTE_LOESCHEN          7242
#define IDC_AUTOSAVE                    7243
#define IDC_AXEL                        7244
#define IDC_BACK                        7245
#define IDC_BAUST_JAHR                  7246
#define IDC_BAUST_MON                   7247
#define IDC_BAUST_TAG                   7248
#define IDC_BAUVORHABEN                 7249
#define IDC_BEARBEITEN                  7250
#define IDC_BEARBEITER                  7251
#define IDC_BEISPIELTXT                 7252
#define IDC_BEMERKUNG                   7253
#define IDC_BENUTZERLOESCHEN            7254
#define IDC_BENUTZERNAME                7255
#define IDC_BLOCK1                      7256
#define IDC_BLOCK2                      7257
#define IDC_BLOCK3                      7258
#define IDC_BOLD                        7259
#define IDC_BRANCHE                     7260
#define IDC_BROWSE                      7261
#define IDC_BTIDENTARTCODE              7262
#define IDC_BTIDENTARTIKELNUMMER        7263
#define IDC_BTIDENTARTKURZTEXT          7264
#define IDC_BTIDENTCODEGRUPPE           7265
#define IDC_BTIDENTKURZTEXTGRUPPE       7266
#define IDC_BTIDENTLISTE                7267
#define IDC_BUTTON_AUFTRAGSINFO         7268
#define IDC_BUTTON_DELETE               7269
#define IDC_BUTTON_EDIT                 7270
#define IDC_BUTTON_ERSTELLEN            7271
#define IDC_BUTTON_KUNDE                7272
#define IDC_BUTTON_LAYOUT               7273
#define IDC_BUTTON_LOESCHEN             7274
#define IDC_BUTTON_NEU                  7275
#define IDC_BUTTON_PRJAUFSCHLAEGE       7276
#define IDC_BUTTON_STANDARD             7277
#define IDC_BUTTON_STD                  7278
#define IDC_BUTTON_TITPREIS             7279
#define IDC_BUTTON_WAEHRUNG             7280
#define IDC_CANCEL                      7281
#define IDC_CHECKGERAMT                 7282
#define IDC_CHECKSHADE                  7283
#define IDC_CHECK_ALLECALC              7284
#define IDC_CHECK_ARTNR                 7285
#define IDC_CHECK_AUTOFORMAT            7286
#define IDC_CHECK_BELEG                 7287
#define IDC_CHECK_EINZELPREIS_LOHN      7288
#define IDC_CHECK_EINZELPREIS_MATERIAL  7289
#define IDC_CHECK_EINZELPREIS_STUNDEN   7290
#define IDC_CHECK_EINZELPREIS_SUMME     7291
#define IDC_CHECK_FORTLAUFEND           7292
#define IDC_CHECK_GEAENDERT             7293
#define IDC_CHECK_GELOESCHT             7294
#define IDC_CHECK_GESAMTPREIS_LOHN      7295
#define IDC_CHECK_GESAMTPREIS_MATERIAL  7296
#define IDC_CHECK_GESAMTPREIS_STUNDEN   7297
#define IDC_CHECK_GESAMTPREIS_SUMME     7298
#define IDC_CHECK_KEIN_UEBERTRAG        7299
#define IDC_CHECK_KURZTEXT              7300
#define IDC_CHECK_LINIEN                7301
#define IDC_CHECK_LOHNAUFSCHLAG         7302
#define IDC_CHECK_MATERIALAUFSCHLAG     7303
#define IDC_CHECK_MENGE                 7304
#define IDC_CHECK_MITPREIS              7305
#define IDC_CHECK_NEU                   7306
#define IDC_CHECK_POSITION              7307
#define IDC_CHECK_PREISE_GETRENNT       7308
#define IDC_CHECK_SHOWLVTXT             7309
#define IDC_CHECK_STANDARD              7310
#define IDC_CHECK_STANDARDCUR           7311
#define IDC_CHECK_TITELNR_AUSGEBEN      7312
#define IDC_CHECK_UNIVERSAL             7313
#define IDC_CHOOSEPATH_KOMP             7314
#define IDC_CHOOSEPATH_PRJ              7315
#define IDC_CHOOSEPATH_SAP              7316
#define IDC_CHOOSEPATH_SPL              7317
#define IDC_CHOOSEPATH_VAA              7318
#define IDC_CHOOSE_EXE                  7319
#define IDC_CHOOSE_TEMPL                7320
#define IDC_CHRISTIAN                   7321
#define IDC_CLOSE_PROJEKT               7322
#define IDC_CODE                        7323
#define IDC_CODEEINGABE                 7324
#define IDC_COLLAPSE                    7325
#define IDC_COLLAPSEALL                 7326
#define IDC_COMBO1                      7327
#define IDC_COMBOBOX_WWVER              7328
#define IDC_COMBO_ABCKLASSE             7329
#define IDC_COMBO_AUFTRAGSERTEILUNG     7330
#define IDC_COMBO_AUFTRAGSSTRUKTUR      7331
#define IDC_COMBO_AUFTRAGSTYP           7332
#define IDC_COMBO_BAUVORHABEN           7333
#define IDC_COMBO_BENUTZER              7334
#define IDC_COMBO_BRANCHE               7335
#define IDC_COMBO_BRANCHE2              7336
#define IDC_COMBO_FONTSIZE              7337
#define IDC_COMBO_KUNDE                 7338
#define IDC_COMBO_KUNDENGRUPPE          7339
#define IDC_COMBO_PREIS                 7340
#define IDC_COMBO_PRODUKTGRUPPE         7341
#define IDC_COMBO_ROUND                 7342
#define IDC_COMBO_TABS                  7343
#define IDC_CONNECTSTRING               7344
#define IDC_COPY                        7345
#define IDC_COUNTOBJECTS                7346
#define IDC_CURSYM                      7347
#define IDC_CURSYMBOL                   7348
#define IDC_CUT                         7349
#define IDC_DATEIENDUNG                 7350
#define IDC_DATENBASIS_ERSTELLEN        7351
#define IDC_DATETIMEPICKER1             7352
#define IDC_DATE_ABGABE                 7353
#define IDC_DATE_ANFRAGE                7354
#define IDC_DATE_VERGABE                7355
#define IDC_DATUM                       7356
#define IDC_DATUM2                      7357
#define IDC_DATUM_EINFUEGEN             7358
#define IDC_DELETE                      7359
#define IDC_DIREKTAUFRUF                7360
#define IDC_DURCHWAHL                   7361
#define IDC_PARA_MAXPOSPERSA            7362
#define IDC_PARA_KENNUNG                7363
#define IDC_PARA_MAXPOSPERSITE          7364
#define IDC_PARA_LIEFERFRIST            7365
#define IDC_PARA_MBTERMIN               7366
#define IDC_EDITPRJ                     7369
#define IDC_VAL                         7369
#define IDC_EDITVAA                     7370
#define IDC_EDIT_AUFTRAGSWERT           7371
#define IDC_EDIT_BEARBEITER             7372
#define IDC_EDIT_BEMERKUNG              7373
#define IDC_EDIT_BEZEICHNUNG            7374
#define IDC_EDIT_DATUM                  7375
#define IDC_EDIT_FACTOR                 7376
#define IDC_EDIT_FACTOR2                7377
#define IDC_EDIT_GESAMTPREIS            7378
#define IDC_EDIT_KOMMENTAR              7379
#define IDC_EDIT_KOMP                   7380
#define IDC_EDIT_KURZTEXT               7381
#define IDC_EDIT_LOHN                   7382
#define IDC_EDIT_LOHNAUFSCHLAG          7383
#define IDC_EDIT_MATERIALAUFSCHLAG      7384
#define IDC_EDIT_MENGE                  7385
#define IDC_EDIT_NAME                   7386
#define IDC_EDIT_PLATZHALTEREP          7387
#define IDC_EDIT_PLATZHALTEREP2         7388
#define IDC_EDIT_PLATZHALTERGP          7389
#define IDC_EDIT_PLATZHALTERGP2         7390
#define IDC_EDIT_POSNR                  7391
#define IDC_EDIT_PRJ                    7392
#define IDC_EDIT_SAP                    7393
#define IDC_EDIT_SPL                    7394
#define IDC_EDIT_TEXT1                  7395
#define IDC_EDIT_TEXT2                  7396
#define IDC_EDIT_VAA                    7397
#define IDC_EDIT_WERT                   7398
#define IDC_EINF                        7399
#define IDC_EINFUEGEN_ANFANG            7400
#define IDC_EINFUEGEN_ENDE              7401
#define IDC_EINFUEGEN_NORMAL            7402
#define IDC_EINZELBESTAET               7403
#define IDC_EMAIL                       7404
#define IDC_ENTF                        7405
#define IDC_EP                          7406
#define IDC_ERSTELLTAM                  7407
#define IDC_ERWEITERT                   7408
#define IDC_EXPAND                      7409
#define IDC_EXPANDALL                   7410
#define IDC_FAKTORZUORDNUNG             7411
#define IDC_FELD1                       7412
#define IDC_FELD2                       7413
#define IDC_FELD3                       7414
#define IDC_FELD4                       7415
#define IDC_FELD5                       7416
#define IDC_FELD6                       7417
#define IDC_FELD7                       7418
#define IDC_FELD8                       7419
#define IDC_FILE1                       7420
#define IDC_FILE2                       7421
#define IDC_FILE3                       7422
#define IDC_FILE4                       7423
#define IDC_FILE5                       7424
#define IDC_FIND                        7425
#define IDC_FIRMA                       7426
#define IDC_FIRST                       7427
#define IDC_FONT0                       7428
#define IDC_FONT1                       7429
#define IDC_FONT2                       7430
#define IDC_FONT3                       7431
#define IDC_FRAGE                       7432
#define IDC_FRAGE2                      7433
#define IDC_GEAENDERT                   7434
#define IDC_GESAMTMONTAGE               7435
#define IDC_GESAMTPREIS                 7436
#define IDC_GITTER                      7437
#define IDC_GP                          7438
#define IDC_HINWEIS                     7439
#define IDC_HINWEIS1                    7440
#define IDC_HINWEIS_NUMMER              7441
#define IDC_HWTEXT                      7442
#define IDC_IHRENACHRICHT               7443
#define IDC_INFO                        7444
#define IDC_ISTFREMDLEISTUNG            7445
#define IDC_ISTSPRINKLER                7446
#define IDC_KALKULATION_BEARBEITEN      7447
#define IDC_KALKULATION_ERSTELLEN       7448
#define IDC_KAROEINSTELLUNGEN           7449
#define IDC_KEINEANGEBOTSAUSGEBE        7450
#define IDC_KONFPRINT                   7451
#define IDC_KOPFOBEN                    7452
#define IDC_KOPFUNTEN                   7453
#define IDC_KOSTENTRAEGER               7454
#define IDC_KOSTENTRAEGER2              7455
#define IDC_KOSTENTRNUMMER              7456
#define IDC_KUNDE                       7457
#define IDC_KUNDENAME                   7458
#define IDC_KUNDENGRUPPE                7459
#define IDC_KUNDENNR                    7460
#define IDC_KUNDENPREISLISTE            7461
#define IDC_KUNDE_NAME                  7462
#define IDC_KURZTEXT                    7463
#define IDC_LANGTEXT                    7464
#define IDC_LAST                        7465
#define IDC_LENGTH                      7466
#define IDC_LINKS                       7467
#define IDC_LIST1                       7468
#define IDC_LIST2                       7469
#define IDC_LISTBOX                     7470
#define IDC_LISTE                       7471
#define IDC_LISTE_ANGEBOT               7472
#define IDC_LISTE_BK                    7473
#define IDC_LISTE_GROSS                 7474
#define IDC_LISTE_LV                    7475
#define IDC_LISTE_VK                    7476
#define IDC_LIST_CURRENCY               7477
#define IDC_LIST_STRINGS                7478
#define IDC_LIST_UPDATE                 7479
#define IDC_LOADATSTART                 7480
#define IDC_LOESCHEN                    7481
#define IDC_LOHN                        7482
#define IDC_MAKROLIST                   7483
#define IDC_MATERIAL                    7484
#define IDC_MENGE                       7485
#define IDC_MONTAGESTD                  7486
#define IDC_MOVETO                      7487
#define IDC_MZ_JAHR                     7488
#define IDC_MZ_MON                      7489
#define IDC_MZ_TAG                      7490
#define IDC_NACHSPANN                   7491
#define IDC_NACHSPANN_LV                7492
#define IDC_NACHTR_SUMPOS               7493
#define IDC_NAME                        7494
#define IDC_NEU                         7495
#define IDC_NEUERBENUTZER               7496
#define IDC_NEW                         7497
#define IDC_NEWPASSWORD                 7498
#define IDC_NICHTIMANGEBOTAUSGEBEN      7499
#define IDC_NICHTVORLEGEN               7500
#define IDC_NOROUND                     7501
#define IDC_NOTROUND                    7502
#define IDC_OBEN                        7503
#define IDC_OK                          7504
#define IDC_OPEN                        7505
#define IDC_PASSWD                      7506
#define IDC_PASSWORD                    7507
#define IDC_PASTE                       7508
#define IDC_PATH_EXE                    7509
#define IDC_PATH_TEMPL                  7510
#define IDC_PETER                       7511
#define IDC_POSITION                    7512
#define IDC_POSITIONEN_KURZTEXT         7513
#define IDC_POSITIONEN_LANGTEXT         7514
#define IDC_POSITIONEN_LVTEXT           7515
#define IDC_POSITIONSNUMMER             7516
#define IDC_POSNR                       7517
#define IDC_POSTITION_ARTNR             7518
#define IDC_POSTITION_BTCODE            7519
#define IDC_POSTITION_DMSTD             7520
#define IDC_POSTITION_GRUPPE            7521
#define IDC_POSTITION_GUELTIGBIS        7522
#define IDC_POSTITION_GUELTIGVON        7523
#define IDC_POSTITION_LISTE             7524
#define IDC_POSTITION_MONTAGESTD        7525
#define IDC_POSTITION_PREIS             7526
#define IDC_POSTITION_WL                7527
#define IDC_POSTITION_WM                7528
#define IDC_PREIS                       7529
#define IDC_PREIS1                      7530
#define IDC_PREIS10                     7531
#define IDC_PREIS2                      7532
#define IDC_PREIS3                      7533
#define IDC_PREIS4                      7534
#define IDC_PREIS5                      7535
#define IDC_PREIS6                      7536
#define IDC_PREIS7                      7537
#define IDC_PREIS8                      7538
#define IDC_PREIS9                      7539
#define IDC_PREISBASIS                  7540
#define IDC_PREISLISTEN                 7541
#define IDC_PREISPROSTD                 7542
#define IDC_PREISUPDATE                 7543
#define IDC_PREV                        7544
#define IDC_PRINT                       7545
#define IDC_PRINT2                      7546
#define IDC_PRINT2_LV                   7547
#define IDC_PRINTALL                    7548
#define IDC_PRINTSTUECKLIST             7549
#define IDC_PRJDATEN_UEBERNAHME         7550
#define IDC_PRJENDUNG                   7551
#define IDC_PRODUKTGRUPPE               7552
#define IDC_PROGRESS                    7553
#define IDC_PROGRESSINDIKATOR           7554
#define IDC_PROJEKTANGABEN              7555
#define IDC_PROJEKTKOMPONENTEN          7556
#define IDC_PROJEKTNUMMER               7557
#define IDC_PROJEKTSTATUS               7558
#define IDC_PROJEKTWL                   7559
#define IDC_PROJEKTWLVK                 7560
#define IDC_PROJEKTWM                   7561
#define IDC_PROJEKTWMVK                 7562
#define IDC_RADIO_ANFRAGE               7563
#define IDC_RADIO_ANGEBOT               7564
#define IDC_RADIO_AUFTRAG               7565
#define IDC_RADIO_DEUTSCH               7566
#define IDC_RADIO_ENGLISH               7567
#define IDC_RADIO_LAYOUT1               7568
#define IDC_RADIO_LAYOUT2               7569
#define IDC_RADIO_LAYOUT3               7570
#define IDC_RADIO_LAYOUT4               7571
#define IDC_RADIO_LAYOUT5               7572
#define IDC_RADIO_SPANANISCH            7573
#define IDC_RADIO_WETTBERWERBER         7574
#define IDC_READFILE                    7575
#define IDC_RECHTS                      7576
#define IDC_ROUND10                     7577
#define IDC_ROUND50                     7578
#define IDC_ROUNDFULL                   7579
#define IDC_RTFCONTROL                  7580
#define IDC_RTF_DUMMY                   7581
#define IDC_RTF_DUMMY_ADRESSE           7582
#define IDC_RTF_DUMMY_SMALL             7583
#define IDC_SACHBEARBEITER              7584
#define IDC_SAVE                        7585
#define IDC_SAVEAS                      7586
#define IDC_SAVEEXT                     7587
#define IDC_SCHRIFTART                  7588
#define IDC_SCHRIFTGROESSE              7589
#define IDC_SEITENUMBRUCH               7590
#define IDC_SEITENVORSCHUB              7591
#define IDC_SELECTALL                   7592
#define IDC_SELECTDOWN                  7593
#define IDC_SELECTUP                    7594
#define IDC_SHOWINFO                    7595
#define IDC_SPEICHERN                   7596
#define IDC_SPEICHERNALS                7597
#define IDC_SPRACHE                     7598
#define IDC_STANDARD                    7599
#define IDC_STANDARDPREISLISTE          7600
#define IDC_STARTUPDATE                 7601
#define IDC_STATIC1                     7602
#define IDC_STATIC2                     7603
#define IDC_STATIC3                     7604
#define IDC_STATIC4                     7605
#define IDC_STATICKUNDENNR              7606
#define IDC_STATIC_1                    7607
#define IDC_STATIC_11                   7608
#define IDC_STATIC_2                    7609
#define IDC_STATIC_3                    7610
#define IDC_STATIC_5                    7611
#define IDC_STATIC_6                    7612
#define IDC_STATIC_7                    7613
#define IDC_STATIC_8                    7614
#define IDC_STATIC_9                    7615
#define IDC_STATIC_BKFREMD              7616
#define IDC_STATIC_BKGESAMT             7617
#define IDC_STATIC_BKLOHN               7618
#define IDC_STATIC_BKMAT                7619
#define IDC_STATIC_DATUM                7620
#define IDC_STATIC_FAKTORMAT            7621
#define IDC_STATIC_FELD1                7622
#define IDC_STATIC_FELD2                7623
#define IDC_STATIC_FELD3                7624
#define IDC_STATIC_FELD4                7625
#define IDC_STATIC_FELD5                7626
#define IDC_STATIC_FELD6                7627
#define IDC_STATIC_FELD7                7628
#define IDC_STATIC_FELD8                7629
#define IDC_STATIC_FELD9                7630
#define IDC_STATIC_GESAMT               7631
#define IDC_STATIC_LAYOUTANZEIGE        7632
#define IDC_STATIC_LOHN                 7633
#define IDC_STATIC_MONTAGESTD           7634
#define IDC_STATIC_NLNR                 7635
#define IDC_STATIC_PREIS_1              7636
#define IDC_STATIC_PREIS_10             7637
#define IDC_STATIC_PREIS_11             7638
#define IDC_STATIC_PREIS_12             7639
#define IDC_STATIC_PREIS_13             7640
#define IDC_STATIC_PREIS_14             7641
#define IDC_STATIC_PREIS_15             7642
#define IDC_STATIC_PREIS_16             7643
#define IDC_STATIC_PREIS_17             7644
#define IDC_STATIC_PREIS_18             7645
#define IDC_STATIC_PREIS_19             7646
#define IDC_STATIC_PREIS_2              7647
#define IDC_STATIC_PREIS_20             7648
#define IDC_STATIC_PREIS_3              7649
#define IDC_STATIC_PREIS_4              7650
#define IDC_STATIC_PREIS_5              7651
#define IDC_STATIC_PREIS_6              7652
#define IDC_STATIC_PREIS_7              7653
#define IDC_STATIC_PREIS_8              7654
#define IDC_STATIC_PREIS_9              7655
#define IDC_STATIC_PRJLTRAUFSCHLAG      7656
#define IDC_STATIC_PRJLTRSTUNDEN        7657
#define IDC_STATIC_SPANZAHL             7658
#define IDC_STATIC_SPLOHN               7659
#define IDC_STATIC_SPMAT                7660
#define IDC_STATIC_VKFREMD              7661
#define IDC_STATIC_VKGESAMT             7662
#define IDC_STATIC_VKLOHN               7663
#define IDC_STATIC_VKMAT                7664
#define IDC_STATIC_VON                  7665
#define IDC_STATUS                      7666
#define IDC_STATUSBMP                   7667
#define IDC_STDSPL                      7668
#define IDC_STOPPUNKTAUFLOESEN          7669
#define IDC_STUECKLISTE                 7670
#define IDC_STUNDENSATZ                 7671
#define IDC_SUCHEN                      7672
#define IDC_SUCHPFAD                    7673
#define IDC_SUCH_TABLENAME              7674
#define IDC_SYSPARAM_LIST               7675
#define IDC_TEXT                        7676
#define IDC_TITPREIS_AUSGEBEN           7677
#define IDC_TITZUS                      7678
#define IDC_TMPFILE                     7679
#define IDC_TRANSLATE                   7680
#define IDC_TRANSLATE_GERMAN            7681
#define IDC_TREE1                       7682
#define IDC_TREEAUFSCHLAEGE             7683
#define IDC_UMRECHNUNGSFAKTOR           7684
#define IDC_UNTEN                       7686
#define IDC_VKLOHN                      7687
#define IDC_VKMATERIAL                  7688
#define IDC_VKPOSITION                  7689
#define IDC_VKSTUECKGESAMT              7690
#define IDC_VKSTUECKGESAMT1             7691
#define IDC_VOLLEBREITE                 7692
#define IDC_VORSPANN                    7693
#define IDC_VORSPANN_LV                 7694
#define IDC_WAEHRUNG                    7695
#define IDC_WERKNORM                    7696
#define IDC_WERT                        7697
#define IDC_WIEDERBESCHAFFUNG           7698
#define IDC_WL                          7699
#define IDC_WL1                         7700
#define IDC_WM                          7701
#define IDC_WM1                         7702
#define IDC_WRITEFILE                   7703
#define IDC_WV_AUTOCHECK                7704
#define IDC_WV_TABLENAME                7705
#define IDC_WV_TAGE                     7706
#define IDC_ZULETZT_ERSTELLT            7707
#define IDC_ZUSATZINFO                  7708
#define IDI_ADRESSEN                    7709
#define IDI_BENUTZER                    7710
#define IDI_HINWEISTEXTE                7711
#define IDI_ICON_NOK                    7712
#define IDI_ICON_NOTHING                7713
#define IDI_ICON_OK                     7714
#define IDI_MARKER                      7715
#define IDI_PREISLISTE                  7716
#define IDI_PROJEKT                     7717
#define IDI_SYSPARAM                    7718
#define IDI_TEXTBAUSTEINE               7719
#define AFX_IDS_APP_TITLE2              7720
#define IDS_ABC_KLASSEN                 7721
#define IDS_ADRESSAUSWAHL_ANSCHRIFT1    7722
#define IDS_ADRESSAUSWAHL_ANSCHRIFT2    7723
#define IDS_ADRESSAUSWAHL_EMAIL         7724
#define IDS_ADRESSAUSWAHL_FAX           7725
#define IDS_ADRESSAUSWAHL_KOMMENTAR     7726
#define IDS_ADRESSAUSWAHL_LAND          7727
#define IDS_ADRESSAUSWAHL_ORT           7728
#define IDS_ADRESSAUSWAHL_STRASSE       7729
#define IDS_ADRESSAUSWAHL_TELEFON       7730
#define IDS_ADRESSCODE_EINGEBEN         7731
#define IDS_ADRESSCODE_EINGEBEN2        7732
#define IDS_ADRESSEN                    7733
#define IDS_AENDERUNGEN_VERWERFEN       7734
#define IDS_AENDERUNGEN_VERWERFEN2      7735
#define IDS_ALLEPOSI                    7736
#define IDS_ANGEBOTSFORM                7737
#define IDS_ANGEBOT_NICHTAUSGEBEN       7738
#define IDS_ANGEBOT_STANDARD            7739
#define IDS_ANSCHR                      7740
#define IDS_ANSPRECHPARTNER             7741
#define IDS_ARTIKELNUMMER               7742
#define IDS_AUFSCHLAG                   7743
#define IDS_AUFSCHLAG_LOHN              7744
#define IDS_AUFSCHLAG_MATERIAL          7745
#define IDS_AUFTRAGGEBER                7746
#define IDS_AUFTRAGSART                 7747
#define IDS_AUFTRAGSBEZ                 7748
#define IDS_AUFTRAGSERTEILUNG           7749
#define IDS_AUFTRAGSMELDUNG             7750
#define IDS_AUFTRAGSTYP                 7751
#define IDS_AUSWERTUNG                  7752
#define IDS_AUTOSAVE                    7753
#define IDS_AXEL                        7754
#define IDS_BAUVORHABEN                 7755
#define IDS_BEENDEN                     7756
#define IDS_BEGRUESSUNG                 7757
#define IDS_BITTEZAHLEINGEBEN           7759
#define IDS_BITTEZAHLEINGEBEN2          7760
#define IDS_BRANCHE                     7761
#define IDS_CHRISTIAN                   7762
#define IDS_CODE                        7763
#define IDS_CODESUCHEN                  7764
#define IDS_COMPLETEFILLREQUIRED        7765
#define IDS_COMPLETEFILLREQUIRED2       7766
#define IDS_COMPLETEFILLREQUIRED3       7767
#define IDS_CONFIRMDELETE               7768
#define IDS_CONVERTSPANXOLD             7769
#define IDS_CREATEVIEW                  7770
#define IDS_DATEIENDUNG                 7771
#define IDS_DATEINAME                   7772
#define IDS_DATEINAME2                  7773
#define IDS_DATENBASIS                  7774
#define IDS_DATENBASIS_ERSTELLT         7775
#define IDS_DATENSATZ_NICHT_GEFUNDEN    7776
#define IDS_DATUM                       7777
#define IDS_DATUMZEITRAUM               7778
#define IDS_DBERROR                     7779
#define IDS_DBLOADING                   7780
#define IDS_STDPFAD                     7780
#define IDS_DBLOADING2                  7781
#define IDC_PARA_APSAD_ROHRE            7781
#define IDS_DBOPENFAILED                7782
#define IDS_DEFFILTER                   7783
#define IDS_UNBEKANNTER_BENUTZER        7783
#define IDS_DEFFILTER2                  7784
#define IDS_FERT_IN_BO                  7784
#define IDS_DELETEITEM                  7785
#define IDS_DIREKTEINGABE               7786
#define IDS_AUFTRAG_ZUR_FREIGABE        7786
#define IDS_DUMUSTNEULADEN              7787
#define IDS_EDITCHANGE                  7788
#define IDS_EDITNOTCHANGE               7789
#define IDS_EIGENLEISTUNG               7790
#define IDS_EINFUEGEN                   7791
#define IDS_EINGABEERFORDERLICH         7792
#define IDS_EINGABE_ERFORDERLICH        7793
#define IDS_EINZELPREIS_LOHN            7794
#define IDS_EINZELPREIS_MATERIAL        7795
#define IDS_EINZELPREIS_STUNDEN         7796
#define IDS_EINZELPREIS_SUMME           7797
#define IDS_EXPORTED                    7798
#define IDS_FAKTOREN                    7799
#define IDS_FAKTOR_GESAMT               7800
#define IDS_FAKTOR_LOHN                 7801
#define IDS_FAKTOR_MAT                  7802
#define IDS_FALSCHEANZAHL               7803
#define IDS_FALSCHESDATUM               7804
#define IDS_FALSCHESPASSWORD            7805
#define IDS_FALSCHESPASSWORD2           7806
#define IDS_FALSCHESPROJEKTFORMAT       7807
#define IDS_FALSCHES_DATEIFORMAT        7808
#define IDS_FALSCHEZAHL                 7809
#define IDS_FEHLER                      7810
#define IDS_FILTERPREISLISTEN           7811
#define IDS_FINDWINWORD                 7812
#define IDS_FREMDLEIST                  7813
#define IDS_GESAMT                      7814
#define IDS_GESAMTDIFF                  7815
#define IDS_GESAMTERGEBNIS              7816
#define IDS_GESAMTPREIS_LOHN            7817
#define IDS_GESAMTPREIS_MATERIAL        7818
#define IDS_GESAMTPREIS_STUNDEN         7819
#define IDS_GESAMTPREIS_SUMME           7820
#define IDS_GRUPPE                      7821
#define IDS_HINWEISTEXTE                7822
#define IDS_INFOANZEIGEN                7823
#define IDS_INFONICHTANZEIGEN           7824
#define IDS_KALKART                     7825
#define IDS_KALKF_AUFSCH                7826
#define IDS_KALKF_PRJAUF                7827
#define IDS_KALK_ARTNR                  7828
#define IDS_KALK_BK                     7829
#define IDS_KALK_BVK                    7830
#define IDS_KALK_FLAG_ARTNR             7831
#define IDS_KALK_FLAG_AUFLOHN           7832
#define IDS_KALK_FLAG_AUFMAT            7833
#define IDS_KALK_FLAG_BEZEICHNUNG       7834
#define IDS_KALK_FLAG_EPLOHN            7835
#define IDS_KALK_FLAG_EPMAT             7836
#define IDS_KALK_FLAG_EPSTD             7837
#define IDS_KALK_FLAG_EPSUMME           7838
#define IDS_KALK_FLAG_GPLOHN            7839
#define IDS_KALK_FLAG_GPMAT             7840
#define IDS_KALK_FLAG_GPSTD             7841
#define IDS_KALK_FLAG_GPSUMME           7842
#define IDS_KALK_FLAG_MENGE             7843
#define IDS_KALK_FLAG_POSNR             7844
#define IDS_KALK_HBK                    7845
#define IDS_KALK_HVK                    7846
#define IDS_KALK_MONTAGE                7847
#define IDS_KALK_USER                   7848
#define IDS_KALK_VK                     7849
#define IDS_KAROISTNICHTLEER            7850
#define IDS_KAROTYPACC                  7851
#define IDS_KAROTYPANGEBOT              7852
#define IDS_KAROTYPANGTEXT              7853
#define IDS_KAROTYPDIR                  7854
#define IDS_KAROTYPEXCEL                7855
#define IDS_KAROTYPFILE                 7856
#define IDS_KAROTYPKALKTEXT             7857
#define IDS_KAROTYPKALKULATION          7858
#define IDS_KAROTYPRECHNUNG             7859
#define IDS_KAROTYPRESERVED10           7860
#define IDS_KAROTYPRESERVED11           7861
#define IDS_KAROTYPRESERVED12           7862
#define IDS_KAROTYPRESERVED13           7863
#define IDS_KAROTYPRESERVED14           7864
#define IDS_KAROTYPRESERVED15           7865
#define IDS_KAROTYPRESERVED4            7866
#define IDS_KAROTYPRESERVED5            7867
#define IDS_KAROTYPRESERVED6            7868
#define IDS_KAROTYPRESERVED7            7869
#define IDS_KAROTYPRESERVED8            7870
#define IDS_KAROTYPRESERVED9            7871
#define IDS_KAROTYPSTART                7872
#define IDS_KAROTYPTEXT                 7873
#define IDS_KAROTYPWORD                 7874
#define IDS_KEINEDATENBASIS             7875
#define IDS_KEINEDATENSAETZE            7876
#define IDS_KEINEINTRAG                 7877
#define IDS_KEINE_ARTIKEL_AUSWEGAEHLT   7878
#define IDS_KEINKAROAUSGEWAEHLT         7879
#define IDS_KNDNR                       7880
#define IDS_KOMPFILTER                  7881
#define IDS_KONFIGURATION               7882
#define IDS_KUNDE                       7883
#define IDS_LABEL_BEZEICHNUNG           7884
#define IDS_LABEL_GPREIS                7885
#define IDS_LABEL_MENGE                 7886
#define IDS_LABEL_POSNR                 7887
#define IDS_LAND                        7888
#define IDS_LOADHW                      7889
#define IDS_LOHNAUFSCHLAG               7890
#define IDS_LVHEADER                    7891
#define IDS_LVPH_EPLOHN1                7892
#define IDS_LVPH_EPLOHN2                7893
#define IDS_LVPH_EPMAT1                 7894
#define IDS_LVPH_EPMAT2                 7895
#define IDS_LVPH_GPLOHN1                7896
#define IDS_LVPH_GPLOHN2                7897
#define IDS_LVPH_GPMAT1                 7898
#define IDS_LVPH_GPMAT2                 7899
#define IDS_LVVORTEXT                   7900
#define IDS_LV_LAYOUT1                  7901
#define IDS_LV_LAYOUT2                  7902
#define IDS_LV_LAYOUT3                  7903
#define IDS_LV_LAYOUT4                  7904
#define IDS_LV_UEBERTRAG                7905
#define IDS_MAGICVERSIONNR              7906
#define IDS_MAKROBEZEICHNUNG            7907
#define IDS_MAKRONAME                   7908
#define IDS_MATERIALAUFSCHLAG           7909
#define IDS_MENGE                       7910
#define IDS_MONTAGEGESAMT               7911
#define IDS_MONTAGEZTMSG                7912
#define IDS_MZVORBAUSTELLENTERMIN       7913
#define IDS_NACHRECHNEN                 7914
#define IDS_NEUEGRP                     7915
#define IDS_NEUESPL                     7916
#define IDS_NICHT_AENDERN               7917
#define IDS_NOAUFTRAGSBEZ               7918
#define IDS_NOAUFTRAGSBEZEICHNUNG       7919
#define IDS_NOAUFTRBEZ                  7920
#define IDS_NOBAKFILE                   7921
#define IDS_NOENTRY                     7922
#define IDS_NOEUROUPDATE                7923
#define IDS_NOHWTEXT                    7924
#define IDS_NOKOSTENTRAEGER             7925
#define IDS_NOLANGUAGEFILE              7926
#define IDS_NOPRJNUMMER                 7927
#define IDS_NOPROJECTDATA               7928
#define IDS_NOPROJECTLOADED             7929
#define IDS_NOPSP                       7930
#define IDS_NOSELECTION                 7931
#define IDS_NOTIMER2                    7932
#define IDS_NOTRANSACT                  7933
#define IDS_NOVELLERROR0                7934
#define IDS_NOVELLERROR1                7935
#define IDS_NOVELLERROR3                7936
#define IDS_NOVELLERROR4                7937
#define IDS_NO_BAKKARO                  7938
#define IDS_OBJECT_ARTIKEL              7939
#define IDS_OBJECT_INDIVIDUELL          7940
#define IDS_OBJECT_SUMME                7941
#define IDS_OBJECT_SUMMEENDE            7942
#define IDS_OBJECT_TEXT                 7943
#define IDS_OBJECT_TITEL                7944
#define IDS_OKPROMPT                    7945
#define IDS_ORT                         7946
#define IDS_PARAMFROMINI                7947
#define IDS_PARTFILTER                  7948
#define IDS_PASSWORD                    7949
#define IDS_PASSWORD2                   7950
#define IDS_PASSWORDCHANGE              7951
#define IDS_PASSWORD_AUSWERTUNG         7952
#define IDS_PASSWORD_FALSCH_BESTAETIGT  7953
#define IDS_PETER                       7954
#define IDS_PFLICHTFELD                 7955
#define IDS_PLZ                         7956
#define IDS_POSEDIT_AUFSCHLAG           7957
#define IDS_POSEDIT_AUFSCHLAG2          7958
#define IDS_POSITION                    7959
#define IDS_POSTFACH                    7960
#define IDS_PREISEGETRENNT              7961
#define IDS_PREISLISTENAUSWAHL          7962
#define IDS_PREISLISTENKOPF             7963
#define IDS_PREISLISTE_BK               7964
#define IDS_PREISLISTE_CODE             7965
#define IDS_PREISLISTE_CODES            7966
#define IDS_PREISLISTE_GESAMT           7967
#define IDS_PREISLISTE_GRUPPE           7968
#define IDS_PREISLISTE_LANGTXT          7969
#define IDS_PREISLISTE_LISTE            7970
#define IDS_PREISLISTE_LOHN             7971
#define IDS_PREISLISTE_LVTXT            7972
#define IDS_PREISLISTE_MAT              7973
#define IDS_PREISLISTE_STD              7974
#define IDS_PREISLISTE_VK               7975
#define IDS_PREISPROSTD_AENDERN         7976
#define IDS_PREISPROSTD_AENDERN2        7977
#define IDS_PREISUPDATE_KURZTEXT        7978
#define IDS_PREISUPDATE_POSNR           7979
#define IDS_PREISUPDATE_PREISDIFFERENZ  7980
#define IDS_PREISUPDATE_STDDIFFERENZ    7981
#define IDS_PREIS_UPDATE                7982
#define IDS_PRINTAUFBEREITUNG1          7983
#define IDS_PRINTAUFBEREITUNG2          7984
#define IDS_PRJINFO0                    7985
#define IDS_PRJINFO1                    7986
#define IDS_PRJINFO2                    7987
#define IDS_PRJINFO3                    7988
#define IDS_PRJLOAD                     7989
#define IDS_PRJNUMMER                   7990
#define IDS_PRJPRINT                    7991
#define IDS_PRJSUCH_ANGEBOTSWERT        7992
#define IDS_PRJSUCH_AUFTRAGSBEZEICHNUNG 7993
#define IDS_PRJSUCH_BEZEICHNUNG         7994
#define IDS_PRJSUCH_COUNT               7995
#define IDS_PRJSUCH_DATEINAME           7996
#define IDS_PRJSUCH_ERSTELLT            7997
#define IDS_PRJSUCH_GEAENDERT           7998
#define IDS_PRJSUCH_HINWEIS             7999
#define IDS_PRJSUCH_KOMMENTAR           8000
#define IDS_PRJSUCH_KUNDE               8001
#define IDS_PRJSUCH_PROJEKTNUMMER       8002
#define IDS_PRJSUCH_SACHBEARBEITER      8003
#define IDS_PRJSUCH_STATUS              8004
#define IDS_PRJSUCH_TERMIN_ANFRAGE      8005
#define IDS_PRJSUCH_TERMIN_ANGEBOTSABGABE 8006
#define IDS_PRJSUCH_TERMIN_VERGABE      8007
#define IDS_PRJSUCH_VORLAGE_AM          8008
#define IDS_PRJ_NEWITEM                 8009
#define IDS_PROJEKTAUFSCHLAG_LOHN       8010
#define IDS_PROJEKTAUFSCHLAG_LOHN2      8011
#define IDS_PROJEKTAUFSCHLAG_MAT        8012
#define IDS_PROJEKTAUFSCHLAG_MAT2       8013
#define IDS_PROJEKTAUFSCHLAG_STUNDEN    8014
#define IDS_PROJEKTAUFSCHLAG_STUNDENSATZ 8015
#define IDS_PROJEKTAUFSCHLAG_SUMME      8016
#define IDS_PROJEKTHINWEIS              8017
#define IDS_PROJEKTNAME                 8018
#define IDS_PROJEKTNUMMER               8019
#define IDS_PROJEKTNUMMER2              8020
#define IDS_PROJEKTSTATUS               8021
#define IDS_PROJEKTSUCHE                8022
#define IDS_PROJEKTVERWALTUNG           8023
#define IDS_PROJEKTVERWALTUNG_AUFTRAGSBEZEICHNUNG 8024
#define IDS_PROJEKTVERWALTUNG_BEMERKUNG 8025
#define IDS_PROJEKTVERWALTUNG_ERSTELLT  8026
#define IDS_PROJEKTVERWALTUNG_GEAENDERT 8027
#define IDS_PROJEKTVERWALTUNG_KUNDE     8028
#define IDS_PROJEKTVERWALTUNG_NUMMER    8029
#define IDS_PROJEKTVERWALTUNG_SACHBEARBEITER 8030
#define IDS_PROJEKTVERWALTUNG_TYP       8031
#define IDS_PROP_CUR_DEFAULT            8032
#define IDS_PROP_CUR_FAKTOR             8033
#define IDS_PROP_CUR_INST               8034
#define IDS_PROP_CUR_PRJMAN             8035
#define IDS_QUUPDATEEURO                8036
#define IDS_QUUPDATEEURO2               8037
#define IDS_RANDBEDINGUNGEN             8038
#define IDS_READONLY                    8039
#define IDS_REGERRROR                   8040
#define IDS_RUNDUNGMELDUNG              8041
#define IDS_SACHBEARBEITER              8042
#define IDS_SAVEBEFOREQUIT              8043
#define IDS_SEARCH                      8044
#define IDS_SEITE                       8045
#define IDS_SEITENUMBRUCH_NOTFOUND2     8046
#define IDS_SPARTE                      8047
#define IDS_SPRINKFAKTOR_GESAMT         8048
#define IDS_SPRINKFAKTOR_LOHN           8049
#define IDS_SPRINKFAKTOR_MAT            8050
#define IDS_STID                        8051
#define IDS_STOPPUNKT_NICHT_AUFGELOEST  8052
#define IDS_STUECKLISTE                 8059
#define IDS_SUCHPFAD                    8060
#define IDS_SUCHSCHEMA                  8061
#define IDS_SUMME_BK                    8062
#define IDS_SUMME_VK                    8063
#define IDS_SYSPARAMNEUERUSER           8064
#define IDS_SYSPARAM_BEMERKUNG          8065
#define IDS_SYSPARAM_NAME               8066
#define IDS_SYSPARAM_NAMEFUERALLE       8067
#define IDS_SYSPARAM_NEUERUSER          8068
#define IDS_SYSPARAM_NODELETE           8069
#define IDS_SYSPARAM_USER               8070
#define IDS_SYSPARAM_WERT               8071
#define IDS_SYSTEMEINSTELLUNG           8072
#define IDS_TBSNOTFOUND                 8073
#define IDS_TELEFON                     8074
#define IDS_TERMIN_LIEGT_IN_VERGANGENHEIT 8075
#define IDS_TEST                        8076
#define IDS_TEST2                       8077
#define IDS_TESTNOVELLRIGHTS0           8078
#define IDS_TESTNOVELLRIGHTS1           8079
#define IDS_TESTOK                      8080
#define IDS_TESTSTATUS                  8081
#define IDS_TESTWINWORD                 8082
#define IDS_TEXTBAUSTEINE               8083
#define IDS_TIT                         8084
#define IDS_TITPREIS_NOTFOUND           8085
#define IDS_TITPREIS_NOTFOUND2          8086
#define IDS_TITZUS                      8087
#define IDS_TRYAGAINQUESTION            8088
#define IDS_UMBENENNEN                  8089
#define IDS_UMRECHUNGSFAKTOR            8090
#define IDS_UNNAMED                     8091
#define IDS_UPDATEERROR                 8092
#define IDS_UPDATE_MISSING              8093
#define IDS_VERSIONSFEHLER              8094
#define IDS_VERSIONSWIRRWARR            8095
#define IDS_VORABANMELDUNG              8096
#define IDS_WAEHRUNG                    8097
#define IDS_WAEHRUNGSKZ                 8098
#define IDS_WELCOME                     8099
#define IDS_WIEDERVORLAGE               8100
#define IDS_WINWORDERROR1               8101
#define IDS_WINWORDERROR10              8102
#define IDS_WINWORDERROR11              8103
#define IDS_WINWORDERROR12              8104
#define IDS_WINWORDERROR13              8105
#define IDS_WINWORDERROR14              8106
#define IDS_WINWORDERROR2               8107
#define IDS_WINWORDERROR3               8108
#define IDS_WINWORDERROR4               8109
#define IDS_WINWORDERROR5               8110
#define IDS_WINWORDERROR6               8111
#define IDS_WINWORDERROR7               8112
#define IDS_WINWORDERROR8               8113
#define IDS_WINWORDERROR9               8114
#define IDS_WINWORDSTART                8115
#define IDS_WORDNOTFOUND                8116
#define IDS_WORDNOTFOUND_DOTPATH        8117
#define IDS_WRONGENTRY                  8118
#define IDS_WRONGKEY                    8119
#define IDS_WWAKTIV                     8120
#define IDS_WWSTAT_1                    8121
#define IDS_WWSTAT_2                    8122
#define IDS_WWSTAT_3                    8123
#define IDS_WWSTAT_4                    8124
#define IDS_WWSTAT_5                    8125
#define CG_IDD_PROGRESS                 8126
#define IDD_ABOUTBOX                    8127
#define IDD_ADRESSVERWALTUNG            8128
#define IDD_ADRESS_SUCHEN               8129
#define IDD_ADRESS_ZUSATZINFO           8130
#define IDD_AUSWAHLPERLISTBOX           8131
#define IDD_AUSWAHLPERMULTILISTBOX      8132
#define IDD_AUSWAHLPERMULTILISTBOXEX    8133
#define IDD_DIALOG_EDIT_CUR             8134
#define IDD_EINGABE                     8136
#define IDD_EINGABE_PASSWORD            8137
#define IDD_FONTSELECT                  8138
#define IDD_HINWEISTEXTVERWALTUNG       8139
#define IDD_KALKULATION_SCHNELLDRUCK    8140
#define IDD_LOGO                        8141
#define IDD_LOGO1                       8142
#define IDD_LV_EINSTELLUNG              8143
#define IDD_LV_LAYOUT                   8144
#define IDD_LV_TITPREIS                 8145
#define IDD_MESSAGE                     8146
#define IDD_MESSAGE_WITH_LOGO           8147
#define IDD_OBJEKTEINSTELLUNGEN         8148
#define IDD_POSITION_ARTIKEL            8149
#define IDD_POSITION_AUFSCHLAGABFRAGE   8150
#define IDD_POSITION_NACHTEXT           8151
#define IDD_POSITION_SUMME              8152
#define IDD_POSITION_TEXT               8153
#define IDD_POSITION_TITEL              8154
#define IDD_POSITION_VORTEXT            8155
#define IDD_PREISLISTENBEARBEITEN       8156
#define IDD_PREISLISTEN_DRUCK           8157
#define IDD_PREISLISTEN_HINWEISINFO     8158
#define IDD_PREISLISTEN_KATALOG         8159
#define IDD_PREISLISTEN_ZUSATZPREISE    8160
#define IDD_PREISLISTE_BAUTEILIDENTIFIKATION 8161
#define IDD_PREISLISTE_INFO             8162
#define IDD_PREISLISTE_STATUS           8163
#define IDD_PROGRESSINDIKATOR           8164
#define IDD_PROJEKTAUSWERTUNG           8165
#define IDD_PROJEKTKAROVERWALTUNG       8166
#define IDD_PROJEKTKAROVERWALTUNG_ANZEIGE 8167
#define IDD_PROJEKTKAROVERWALTUNG_EINSTELLUNGEN 8168
#define IDD_PROJEKTKAROVERWALTUNG_FAKTOREN 8169
#define IDD_PROJEKTKAROVERWALTUNG_INFO  8170
#define IDD_PROJEKTKOPF_AUFTRAGSMELDUNG 8171
#define IDD_PROJEKTKOPF_BAUHERREN       8172
#define IDD_PROJEKTKOPF_HINWEISE        8173
#define IDD_PROJEKTKOPF_RANDBEDINGUNGEN 8174
#define IDD_PROJEKTLEITER_AUFSCHLAG     8175
#define IDD_PROJEKTSTATUS               8176
#define IDD_PROJEKTSTATUS2              8177
#define IDD_PROJEKTSUCHE                8178
#define IDD_PROJEKTVERWALTUNG           8179
#define IDD_PROJEKTWIEDERVORLAGE        8180
#define IDD_PROJEKT_PREISUPDATE         8181
#define IDD_PROP_ALLGEMEIN              8182
#define IDD_PROP_BENUTZER               8183
#define IDD_PROP_CUR_EDIT               8184
#define IDD_PROP_ERWEITERT              8185
#define IDD_PROP_NL2000                 8186
#define IDD_PROP_PFAD                   8187
#define IDD_PROP_WAEHRUNG               8188
#define IDD_PROP_WINWORD                8189
#define IDD_RTFTOTXT                    8190
#define IDD_SEARCHRESULT                8191
#define IDD_SEITENFORMATIERUNG          8192
#define IDD_SPANXLOGO                   8193
#define IDD_SPANXMESSAGE                8194
#define IDD_SPANX_CLIENTAREA            8195
#define IDD_SPANX_CLIENTAREA1           8196
#define IDD_STOPPUNKTAUFLOESEN          8197
#define IDD_STUECKLISTE                 8198
#define IDD_STUECKLISTE_EINGEBEN        8199
#define IDD_SYSPARAM_CHECK              8200
#define IDD_TESTRESOURCE                8201
#define IDD_TEXTBAUSTEINVERWALTUNG      8202
#define IDD_TMPFILES                    8203
#define IDD_WAEHRUNGSEINSTELLUNGEN      8204
#define IDD_PARA_ANSICHT                8205
#define IDD_PARA_BENUTZER               8206
#define IDD_PARA_USER                   8206
#define IDD_PARA_PROJEKT                8209
#define IDD_PARA_ALLGEMEIN              8210
#define IDD_PARA_GEWINDEROHR            8211
#define IDD_PARA_FREIGABESTATUS         8212
#define IDD_PARA_GRAPHIK                8213
#define IDS_PARAMETEREINST              8251
#define IDS_BROWSEFILE                  8252
#define IDD_PARA_SYSALL                 8253
#define IDS_PARAMETEREINST2             8253
#define IDD_PASSWD                      8297
#define IDD_EDIT_PARAMETER              8298
#define IDB_TRENNSTRICH                 8301
#define IDB_TRENNSTRICH1                8302
#define IDB_TRENNSTRICH5                8302
#define IDB_TRENNSTRICH_KURZ            8302
#define IDD_PASSWD_AENDERN              8302
#define IDB_TRENNSTRICH2                8303
#define IDB_TRENNSTRICH6                8303
#define IDB_TRENNSTRICH3                8304
#define IDC_TREECOLOR                   8305
#define IDC_BEISPIEL_KURZ               8306
#define IDC_BEISPIEL_MITTEL             8307
#define IDC_BEISPIEL_LANG               8308
#define IDC_PARA_SAFESTATUS             10204
#define IDC_PARA_SHOWFREIGABEPOS        10205
#define IDC_PARA_BAUMFARBE              10206
#define IDC_PARA_ICONGROSS              10207
#define IDC_PARA_ICONMITTEL             10208
#define IDC_PARA_ICONKLEIN              10209
#define IDC_STANDARD_ANSICHT            10210
#define IDC_PARA_STATUSLEISTE           10211
#define IDC_PARA_GRAPHIKFENSTER         10212
#define IDC_PARA_SPRACHEDEUTSCH         10213
#define IDC_PARA_SPRACHEENGLISCH        10214
#define IDC_PARA_SYMBOLLEISTE           10215
#define IDC_STANDARD_GEWINDEROHR        10216
#define IDC_PARA_BEMASSUNGSLINIE        10217
#define IDC_PARA_BESCHRIFTUNGLAENGE     10218
#define IDC_PARA_RAHMEN                 10219
#define IDC_PARA_TRENNLINIE             10220
#define IDC_STANDARD_GRAPHIK            10221
#define IDS_STRING10221                 10221
#define IDC_PARA_GRAFIKFORMAT           10221
#define IDC_PROJEKTPFAD                 10222
#define IDC_PROJEKT                     10222
#define IDC_STANDARD_EMAIL              10223
#define IDC_EXCEL                       10224
#define IDC_STANDARD_PFADE              10225
#define IDC_PARA_CHECKSAP               10226
#define IDC_STANDARD_SYSTEM             10227
#define IDC_PARA_STAMMDB                10228
#define IDC_PARA_SERVERDB               10229
#define IDC_SAPSOAPSERVER               10229
#define IDC_STANDARD_PROJEKT            10230
#define IDC_PARA_LANGUAGE               10230
#define IDC_PARA_AUTOSAVE               10231
#define IDC_PARA_TRENNZEICHEN           10232
#define IDC_PARA_FONTGROESSE            10233
#define IDC_PARA_PROJEKTPFAD            10234
#define IDC_PARA_ELEBREITE              10234
#define IDC_PARA_ICONGROESSE            10234
#define IDC_PARA_EMPFAENGER             10235
#define IDC_PARA_ELELAENGE              10235
#define IDC_PARA_PROJEKTE               10236
#define IDC_PARA_KOMPPFAD               10237
#define IDC_PARA_DN2ZOLL                10237
#define IDC_PARA_CHECKWA                10238
#define IDC_PARA_WINKELAUSRICHTUNG      10238
#define IDC_PARA_DISPLAY                10239
#define IDC_PARA_ZMASSLISTE             10240
#define IDC_PARA_AUTOFREIGABE           10241
#define IDC_PARA_AV                     10242
#define IDC_PARA_KOMP                   10243
#define IDC_PARA_DN                     10244
#define IDC_PARA_BETREFF                10245
#define IDC_PARA_CHECKSTATUS            10246
#define IDC_PARA_EXCEL                  10247
#define IDC_PARA_ZOLL                   10248
#define IDC_STANDARD_FREIGABE           10249
#define IDC_PARA_TEXTFORMAT             10249
#define IDC_PARA_TEXTKURZ               10250
#define IDC_PARA_TEXTMITTEL             10251
#define IDC_STANDARD_ALLGEMEIN          10252
#define IDC_PARA_LOGDB                  10252
#define IDC_PARA_TEXTLANG               10253
#define IDC_KOMPPFAD                    10254
#define IDC_KOMP                        10254
#define IDC_PARA_BEARBEITER             10254
#define IDC_PARA_WINKEL                 10255
#define IDC_PARA_AUSRICHTUNG            10256
#define IDC_PARA_SAFEFREIGABE           10257
#define IDC_PARA_ZMASSGRAPHIK           10258
#define IDC_PARA_DEBUGNL                10259
#define IDC_PARA_VIEWERDRUCK            10260
#define IDC_PARA_GF_DN2ZOLL             10261
#define IDC_PARA_VIEWERVORSCHAU         10262
#define IDC_EDIT                        10263
#define IDC_PARA_GF_ELELAENGE           10263
#define IDC_STAMMDB                     10264
#define IDC_PARA_GF_ELEBREITE           10264
#define IDC_PARA_LOGIN                  10265
#define IDC_LOGDB                       10265
#define IDC_PARA_BENUTZERNAME           10266
#define IDC_PARA_KURZZEICHEN            10267
#define IDC_PARA_GF_DWFHOEHE            10267
#define IDC_PARA_DURCHWAHL              10268
#define IDC_PARA_EMAIL                  10269
#define IDS_CANCEL                      10270
#define IDC_BREITE                      10271
#define IDS_USER                        10271
#define IDC_LAENGE                      10272
#define IDS_MACHINE                     10272
#define IDS_LOCATION                    10273
#define IDC_STATIC_MBTERMIN             10274
#define IDC_PARA_STATUSZEILE            10274
#define IDC_PARA_DIR_DOC                10275
#define IDC_PARA_MAXPOSPERPAGE          10276
#define ID_STANDARD_SETZEN              10277
#define IDC_MSG                         10278
#define IDS_EXAMPLE3                    10278
#define IDS_EXAMPLE2                    10279
#define IDC_TXT_WERT                    10280
#define IDS_EXAMPLE1                    10280
#define IDC_LOCATION                    10281
#define IDC_ICONKLEIN                   10285
#define IDC_ICONMITTEL                  10286
#define IDC_ICONGROSS                   10287
#define IDC_EXAMPLE1                    10288
#define IDC_PARA_REL_ABST_AENDERN       10289
#define IDC_EXAMPLE2                    10289
#define IDC_PARA_PRINT_WORD             10290
#define IDC_EXAMPLE3                    10290
#define IDC_PARA_DISPLAYNAME            10291
#define IDC_ZMASSLISTE                  10291
#define IDC_PARA_DIR_GROHR_FREE         10292
#define IDC_ZMASSGRAPHIK                10292
#define IDC_PARA_DIR_GROHR_ACTIVE       10293
#define IDC_WINKEL                      10293
#define IDC_PARA_DIR_GROHR_STOPPED      10294
#define IDC_AUSRICHTUNG                 10294
#define IDC_PARA_DIR_GROHR_FINISHED     10295
#define IDC_DN                          10295
#define IDC_PARA_DIR_GROHR_ARCHIVE      10296
#define IDC_ZOLL                        10296
#define IDC_PARA_DIR_SAEGENUT_FREE      10297
#define IDC_TEXTKURZ                    10297
#define IDC_PARA_DIR_SAEGENUT_ACTIVE    10298
#define IDC_TEXTMITTEL                  10298
#define IDC_PARA_DIR_SAEGENUT_STOPPED   10299
#define IDC_TEXTLANG                    10299
#define IDC_PARA_DIR_SAEGENUT_FINISHED  10300
#define IDC_PARA_DIR_SAEGENUT_ARCHIVE   10301
#define IDC_MACHINE                     10301
#define IDC_PARA_DIR_VERTEILER_FREE     10302
#define IDC_RADIO3                      10302
#define IDC_USER                        10302
#define IDC_PARA_DIR_VERTEILER1_ACTIVE  10303
#define IDC_PARA_DIR_VERTEILER1_STOPPED 10304
#define IDC_EDIT2                       10304
#define IDC_SCROLLBAR1                  10304
#define IDC_PARA_DIR_VERTEILER1_FINISHED 10305
#define IDC_PARA_IB_NL_KENNUNG          10305
#define IDC_PARA_DIR_VERTEILER2_ACTIVE  10306
#define IDC_STATIC_AUTOSAVE             10306
#define IDC_PARA_DIR_VERTEILER2_STOPPED 10307
#define IDC_STATIC_ASAVE                10307
#define IDC_PARA_DIR_VERTEILER2_FINISHED 10308
#define IDC_STATIC_SPRACHE              10308
#define IDC_PARA_DIR_VERTEILER_ARCHIVE  10309
#define IDC_STATIC_ICON                 10309
#define IDC_PARA_DIR_STRANG_FREE        10310
#define IDC_STATIC_HFARBE               10310
#define IDC_PARA_DIR_STRANG1_ACTIVE     10311
#define IDC_STATIC_EINGESTELLT          10311
#define IDC_PARA_DIR_STRANG1_STOPPED    10312
#define IDC_STATIC_ANZEIGE              10312
#define IDC_PARA_DIR_STRANG1_FINISHED   10313
#define IDC_STATIC_PROJEKT              10313
#define IDC_PARA_DIR_STRANG2_ACTIVE     10314
#define IDC_STATIC_KO                   10314
#define IDC_PARA_DIR_STRANG2_STOPPED    10315
#define IDC_STATIC_AUFTRAGTAB           10315
#define IDC_PARA_DIR_STRANG2_FINISHED   10316
#define IDC_STATIC_PFADE                10316
#define IDC_PARA_DIR_STRANG3_ACTIVE     10317
#define IDC_STATIC_DB                   10317
#define IDC_PARA_DIR_STRANG3_STOPPED    10318
#define IDC_STATIC_STAMMDB              10318
#define IDC_PARA_DIR_STRANG3_FINISHED   10319
#define IDC_STATIC_LEITK                10319
#define IDC_PARA_DIR_STRANG4_ACTIVE     10320
#define IDC_STATIC_BNR                  10320
#define IDC_PARA_DIR_STRANG4_STOPPED    10321
#define IDC_STATIC_LFRIST               10321
#define IDC_PARA_DIR_STRANG4_FINISHED   10322
#define IDC_STATIC_KURZTXT              10322
#define IDC_STATIC_SAPSOAP_SERVER       10322
#define IDC_PARA_DIR_STRANG_ARCHIVE     10323
#define IDC_STATIC_TRENNZEICHEN         10323
#define IDC_PARA_DIR_STATISTIK          10324
#define IDC_STATIC_ZMASSABZ             10324
#define IDC_PARA_DIR_WAXTOSAP           10325
#define IDC_STATIC_WINKELAUS            10325
#define IDC_PARA_DIR_SAPTOWAX           10326
#define IDC_STATIC_NENNWEITE            10326
#define IDC_PARA_DIR_WAXAPAX            10327
#define IDC_STATIC_DRUCKLISTE           10327
#define IDC_PARA_DIR_WAXAPAX_OLD        10328
#define IDC_STATIC_FONTGROESSE          10328
#define IDC_PARA_DIR_WAXOLD             10329
#define IDC_STATIC_DWF                  10329
#define IDC_STATIC_VORSCHAU             10330
#define IDC_STATIC_GRAFIKFORMAT         10331
#define IDC_STATIC_LOGIN                10332
#define IDC_STATIC_NAME                 10333
#define IDC_STATIC_TEL                  10334
#define IDC_STATIC_EMAIL                10335
#define IDC_STATIC_FREIGABE             10336
#define IDC_STATIC_STATUS               10337
#define IDC_STATIC_EMAILFERT            10338
#define IDC_STATIC_EMAILADR             10339
#define IDC_STATIC_EMPF_BEZ             10340
#define IDC_STATIC_BETREFF              10341
#define IDC_STATIC_NEWPWD               10342
#define IDC_STATIC_NEWPWD_OK            10343
#define IDC_STATIC_GUELTIGKEIT          10344
#define IDC_PARA_SAP_MAT_TO_WAX_EXE     10345
#define IDC_PARA_SAP_MAT_TO_WAX_DAT     10346
#define IDC_PARA_DIR_VERTEILER_FREE_USB 10347
#define IDC_PARA_SAPSOAPSERVER          10348
#define IDC_PARA_DIR_SAPTOWAXWITTENBERGE 10349

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        8303
#define _APS_NEXT_COMMAND_VALUE         9209
#define _APS_NEXT_CONTROL_VALUE         10350
#define _APS_NEXT_SYMED_VALUE           10205
#endif
#endif
