/* matt.h
   Generated by wsdl2h 2.8.17r from CAD_MCC.wsdl and typemap.dat
   2014-09-05 11:26:36 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

   gSOAP XML Web services tools.
   Copyright (C) 2000-2013 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/** @page page_notes Usage Notes

NOTE:

 - Run soapcpp2 on matt.h to generate the SOAP/XML processing logic.
   Use soapcpp2 -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
   Use soapcpp2 -j to generate improved proxy and server classes.
 - Use wsdl2h -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -R to generate REST operations.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Use wsdl2h -d to enable DOM support for xsd:anyType.
 - Use wsdl2h -g to auto-generate readers and writers for root elements.
 - Use wsdl2h -b to auto-generate bi-directional operations (duplex ops).
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

WARNING:

   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

LICENSE:

@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.

This software is released under one of the following licenses:
GPL or Genivia's license for commercial use.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   urn:sap-com:document:sap:soap:functions:mc-style                         *
 *                                                                            *
\******************************************************************************/

/* WSDL Documentation:

<sidl:sidl xmlns:sidl="http://www.sap.com/2007/03/sidl"/>
*/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


// STL vector containers (use option -s to remove STL dependency)
#import "stlvector.h"

/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "urn:sap-com:document:sap:soap:functions:mc-style"
ns2 = "urn:sap-com:document:sap:rfc:functions"

*/

#define SOAP_NAMESPACE_OF_ns2	"urn:sap-com:document:sap:rfc:functions"
//gsoap ns2   schema namespace:	urn:sap-com:document:sap:rfc:functions
//gsoap ns2   schema elementForm:	unqualified
//gsoap ns2   schema attributeForm:	qualified

#define SOAP_NAMESPACE_OF_ns1	"urn:sap-com:document:sap:soap:functions:mc-style"
//gsoap ns1   schema namespace:	urn:sap-com:document:sap:soap:functions:mc-style
//gsoap ns1   schema elementForm:	unqualified
//gsoap ns1   schema attributeForm:	qualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/// Built-in type "xs:base64Binary".
class xsd__base64Binary
{	unsigned char *__ptr;
	int __size;
	char *id, *type, *options; // NOTE: non-NULL for DIMEM/MIME/MTOM XOP attachments only
	struct soap *soap;
};

/// Primitive built-in type "xs:decimal"
typedef std::string xsd__decimal;

/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/



//  Forward declaration of class ns1__ZplmMccNodeHierarchy.
class ns1__ZplmMccNodeHierarchy;

//  Forward declaration of class ns1__ZplmMccPosition.
class ns1__ZplmMccPosition;

//  Forward declaration of class ns1__Bapiret2.
class ns1__Bapiret2;

//  Forward declaration of class ns1__ZplmMccNodeHierarchyT.
class ns1__ZplmMccNodeHierarchyT;

//  Forward declaration of class ns1__ZplmMccPositionT.
class ns1__ZplmMccPositionT;

//  Forward declaration of class ns1__Bapiret2T.
class ns1__Bapiret2T;

//  Forward declaration of class _ns1__ZPlmMccCadCreateMatpl.
class _ns1__ZPlmMccCadCreateMatpl;

//  Forward declaration of class _ns1__ZPlmMccCadCreateMatplResponse.
class _ns1__ZPlmMccCadCreateMatplResponse;

/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   urn:sap-com:document:sap:rfc:functions                                   *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   urn:sap-com:document:sap:soap:functions:mc-style                         *
 *                                                                            *
\******************************************************************************/


/// "urn:sap-com:document:sap:rfc:functions":byte16 is a simpleType restriction of xs:base64Binary.
/// Length of this string is within 0..16 characters
typedef xsd__base64Binary ns2__byte16:16;

/// "urn:sap-com:document:sap:rfc:functions":char1 is a simpleType restriction of xs:string.
/// Length of this string is within 0..1 characters
typedef std::string ns2__char1:1;

/// "urn:sap-com:document:sap:rfc:functions":char10 is a simpleType restriction of xs:string.
/// Length of this string is within 0..10 characters
typedef std::string ns2__char10:10;

/// "urn:sap-com:document:sap:rfc:functions":char18 is a simpleType restriction of xs:string.
/// Length of this string is within 0..18 characters
typedef std::string ns2__char18:18;

/// "urn:sap-com:document:sap:rfc:functions":char2 is a simpleType restriction of xs:string.
/// Length of this string is within 0..2 characters
typedef std::string ns2__char2:2;

/// "urn:sap-com:document:sap:rfc:functions":char20 is a simpleType restriction of xs:string.
/// Length of this string is within 0..20 characters
typedef std::string ns2__char20:20;

/// "urn:sap-com:document:sap:rfc:functions":char220 is a simpleType restriction of xs:string.
/// Length of this string is within 0..220 characters
typedef std::string ns2__char220:220;

/// "urn:sap-com:document:sap:rfc:functions":char3 is a simpleType restriction of xs:string.
/// Length of this string is within 0..3 characters
typedef std::string ns2__char3:3;

/// "urn:sap-com:document:sap:rfc:functions":char30 is a simpleType restriction of xs:string.
/// Length of this string is within 0..30 characters
typedef std::string ns2__char30:30;

/// "urn:sap-com:document:sap:rfc:functions":char32 is a simpleType restriction of xs:string.
/// Length of this string is within 0..32 characters
typedef std::string ns2__char32:32;

/// "urn:sap-com:document:sap:rfc:functions":char4 is a simpleType restriction of xs:string.
/// Length of this string is within 0..4 characters
typedef std::string ns2__char4:4;

/// "urn:sap-com:document:sap:rfc:functions":char40 is a simpleType restriction of xs:string.
/// Length of this string is within 0..40 characters
typedef std::string ns2__char40:40;

/// "urn:sap-com:document:sap:rfc:functions":char50 is a simpleType restriction of xs:string.
/// Length of this string is within 0..50 characters
typedef std::string ns2__char50:50;

/// "urn:sap-com:document:sap:rfc:functions":char9 is a simpleType restriction of xs:string.
/// Length of this string is within 0..9 characters
typedef std::string ns2__char9:9;

/// "urn:sap-com:document:sap:rfc:functions":lang is a simpleType restriction of xs:string.
/// Length of this string is within 0..1 characters
typedef std::string ns2__lang:1;

/// "urn:sap-com:document:sap:rfc:functions":numeric3 is a simpleType restriction of xs:string.
/// Length of this string is within 0..3 characters
/// Content pattern is "\\d*" (note: not automatically enforced)
typedef std::string ns2__numeric3 "\\d*":3;

/// "urn:sap-com:document:sap:rfc:functions":numeric6 is a simpleType restriction of xs:string.
/// Length of this string is within 0..6 characters
/// Content pattern is "\\d*" (note: not automatically enforced)
typedef std::string ns2__numeric6 "\\d*":6;

/// "urn:sap-com:document:sap:rfc:functions":quantum13.3 is a simpleType restriction of xs:decimal.
/// number of total digits is 13 (note: not automatically enforced)
/// number of fraction digits is 3 (note: not automatically enforced)
typedef xsd__decimal ns2__quantum13_x002e3;

/// "urn:sap-com:document:sap:rfc:functions":unit3 is a simpleType restriction of xs:string.
/// Length of this string is within 0..3 characters
typedef std::string ns2__unit3:3;

/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   urn:sap-com:document:sap:soap:functions:mc-style                         *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   urn:sap-com:document:sap:rfc:functions                                   *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   urn:sap-com:document:sap:soap:functions:mc-style                         *
 *                                                                            *
\******************************************************************************/


/// "urn:sap-com:document:sap:soap:functions:mc-style":ZplmMccNodeHierarchy is a complexType.
/// class ns1__ZplmMccNodeHierarchy operations:
/// - soap_new_ns1__ZplmMccNodeHierarchy(soap*) allocate
/// - soap_new_ns1__ZplmMccNodeHierarchy(soap*, int num) allocate array
/// - soap_new_req_ns1__ZplmMccNodeHierarchy(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__ZplmMccNodeHierarchy(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__ZplmMccNodeHierarchy(soap*, ns1__ZplmMccNodeHierarchy*) deserialize from a stream
/// - int soap_write_ns1__ZplmMccNodeHierarchy(soap, ns1__ZplmMccNodeHierarchy*) serialize to a stream
class ns1__ZplmMccNodeHierarchy
{ public:
/// Element Extident of type "urn:sap-com:document:sap:rfc:functions":char20.
    ns2__char20                          Extident                       1;	///< Required element.
/// Element ExtidentParent of type "urn:sap-com:document:sap:rfc:functions":char20.
    ns2__char20                          ExtidentParent                 1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "urn:sap-com:document:sap:soap:functions:mc-style":ZplmMccPosition is a complexType.
/// class ns1__ZplmMccPosition operations:
/// - soap_new_ns1__ZplmMccPosition(soap*) allocate
/// - soap_new_ns1__ZplmMccPosition(soap*, int num) allocate array
/// - soap_new_req_ns1__ZplmMccPosition(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__ZplmMccPosition(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__ZplmMccPosition(soap*, ns1__ZplmMccPosition*) deserialize from a stream
/// - int soap_write_ns1__ZplmMccPosition(soap, ns1__ZplmMccPosition*) serialize to a stream
class ns1__ZplmMccPosition
{ public:
/// Element Extident of type "urn:sap-com:document:sap:rfc:functions":char20.
    ns2__char20                          Extident                       1;	///< Required element.
/// Element Pname of type "urn:sap-com:document:sap:rfc:functions":char40.
    ns2__char40                          Pname                          1;	///< Required element.
/// Element Pnguid of type "urn:sap-com:document:sap:rfc:functions":byte16.
    ns2__byte16                          Pnguid                         1;	///< Required element.
/// Element Material of type "urn:sap-com:document:sap:rfc:functions":char18.
    ns2__char18                          Material                       1;	///< Required element.
/// Element Class of type "urn:sap-com:document:sap:rfc:functions":char18.
    ns2__char18                          Class                          1;	///< Required element.
/// Element Classtype of type "urn:sap-com:document:sap:rfc:functions":char3.
    ns2__char3                           Classtype                      1;	///< Required element.
/// Element Langu of type "urn:sap-com:document:sap:rfc:functions":lang.
    ns2__lang                            Langu                          1;	///< Required element.
/// Element LanguIso of type "urn:sap-com:document:sap:rfc:functions":char2.
    ns2__char2                           LanguIso                       1;	///< Required element.
/// Element MatlDesc of type "urn:sap-com:document:sap:rfc:functions":char40.
    ns2__char40                          MatlDesc                       1;	///< Required element.
/// Element DsnOffice of type "urn:sap-com:document:sap:rfc:functions":char3.
    ns2__char3                           DsnOffice                      1;	///< Required element.
/// Element ProdHier of type "urn:sap-com:document:sap:rfc:functions":char18.
    ns2__char18                          ProdHier                       1;	///< Required element.
/// Element MatlGroup of type "urn:sap-com:document:sap:rfc:functions":char9.
    ns2__char9                           MatlGroup                      1;	///< Required element.
/// Element MfrNo of type "urn:sap-com:document:sap:rfc:functions":char10.
    ns2__char10                          MfrNo                          1;	///< Required element.
/// Element ManuMat of type "urn:sap-com:document:sap:rfc:functions":char40.
    ns2__char40                          ManuMat                        1;	///< Required element.
/// Element ItemNo of type "urn:sap-com:document:sap:rfc:functions":char4.
    ns2__char4                           ItemNo                         1;	///< Required element.
/// Element ItemCat of type "urn:sap-com:document:sap:rfc:functions":char1.
    ns2__char1                           ItemCat                        1;	///< Required element.
/// Element CompQty of type "urn:sap-com:document:sap:rfc:functions":quantum13.3.
    ns2__quantum13_x002e3                CompQty                        1;	///< Required element.
/// Element CompUnit of type "urn:sap-com:document:sap:rfc:functions":unit3.
    ns2__unit3                           CompUnit                       1;	///< Required element.
/// Element CompUnitIso of type "urn:sap-com:document:sap:rfc:functions":char3.
    ns2__char3                           CompUnitIso                    1;	///< Required element.
/// Element SortString of type "urn:sap-com:document:sap:rfc:functions":char10.
    ns2__char10                          SortString                     1;	///< Required element.
/// Element EngRel of type "urn:sap-com:document:sap:rfc:functions":char1.
    ns2__char1                           EngRel                         1;	///< Required element.
/// Element ProdRel of type "urn:sap-com:document:sap:rfc:functions":char1.
    ns2__char1                           ProdRel                        1;	///< Required element.
/// Element Spproctype of type "urn:sap-com:document:sap:rfc:functions":char2.
    ns2__char2                           Spproctype                     1;	///< Required element.
/// Element RefPoint of type "urn:sap-com:document:sap:rfc:functions":char20.
    ns2__char20                          RefPoint                       1;	///< Required element.
/// Element ItemText1 of type "urn:sap-com:document:sap:rfc:functions":char40.
    ns2__char40                          ItemText1                      1;	///< Required element.
/// Element ItemText2 of type "urn:sap-com:document:sap:rfc:functions":char40.
    ns2__char40                          ItemText2                      1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "urn:sap-com:document:sap:soap:functions:mc-style":Bapiret2 is a complexType.
/// class ns1__Bapiret2 operations:
/// - soap_new_ns1__Bapiret2(soap*) allocate
/// - soap_new_ns1__Bapiret2(soap*, int num) allocate array
/// - soap_new_req_ns1__Bapiret2(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__Bapiret2(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__Bapiret2(soap*, ns1__Bapiret2*) deserialize from a stream
/// - int soap_write_ns1__Bapiret2(soap, ns1__Bapiret2*) serialize to a stream
class ns1__Bapiret2
{ public:
/// Element Type of type "urn:sap-com:document:sap:rfc:functions":char1.
    ns2__char1                           Type                           1;	///< Required element.
/// Element Id of type "urn:sap-com:document:sap:rfc:functions":char20.
    ns2__char20                          Id                             1;	///< Required element.
/// Element Number of type "urn:sap-com:document:sap:rfc:functions":numeric3.
    ns2__numeric3                        Number                         1;	///< Required element.
/// Element Message of type "urn:sap-com:document:sap:rfc:functions":char220.
    ns2__char220                         Message                        1;	///< Required element.
/// Element LogNo of type "urn:sap-com:document:sap:rfc:functions":char20.
    ns2__char20                          LogNo                          1;	///< Required element.
/// Element LogMsgNo of type "urn:sap-com:document:sap:rfc:functions":numeric6.
    ns2__numeric6                        LogMsgNo                       1;	///< Required element.
/// Element MessageV1 of type "urn:sap-com:document:sap:rfc:functions":char50.
    ns2__char50                          MessageV1                      1;	///< Required element.
/// Element MessageV2 of type "urn:sap-com:document:sap:rfc:functions":char50.
    ns2__char50                          MessageV2                      1;	///< Required element.
/// Element MessageV3 of type "urn:sap-com:document:sap:rfc:functions":char50.
    ns2__char50                          MessageV3                      1;	///< Required element.
/// Element MessageV4 of type "urn:sap-com:document:sap:rfc:functions":char50.
    ns2__char50                          MessageV4                      1;	///< Required element.
/// Element Parameter of type "urn:sap-com:document:sap:rfc:functions":char32.
    ns2__char32                          Parameter                      1;	///< Required element.
/// Element Row of type xs:int.
    int                                  Row                            1;	///< Required element.
/// Element Field of type "urn:sap-com:document:sap:rfc:functions":char30.
    ns2__char30                          Field                          1;	///< Required element.
/// Element SYSTEM of type "urn:sap-com:document:sap:rfc:functions":char10.
    ns2__char10                          SYSTEM                         1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "urn:sap-com:document:sap:soap:functions:mc-style":ZplmMccNodeHierarchyT is a complexType.
/// class ns1__ZplmMccNodeHierarchyT operations:
/// - soap_new_ns1__ZplmMccNodeHierarchyT(soap*) allocate
/// - soap_new_ns1__ZplmMccNodeHierarchyT(soap*, int num) allocate array
/// - soap_new_req_ns1__ZplmMccNodeHierarchyT(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__ZplmMccNodeHierarchyT(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__ZplmMccNodeHierarchyT(soap*, ns1__ZplmMccNodeHierarchyT*) deserialize from a stream
/// - int soap_write_ns1__ZplmMccNodeHierarchyT(soap, ns1__ZplmMccNodeHierarchyT*) serialize to a stream
class ns1__ZplmMccNodeHierarchyT
{ public:
/// Vector of ns1__ZplmMccNodeHierarchy* with length 0..unbounded
    std::vector<ns1__ZplmMccNodeHierarchy*> item                           0;
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "urn:sap-com:document:sap:soap:functions:mc-style":ZplmMccPositionT is a complexType.
/// class ns1__ZplmMccPositionT operations:
/// - soap_new_ns1__ZplmMccPositionT(soap*) allocate
/// - soap_new_ns1__ZplmMccPositionT(soap*, int num) allocate array
/// - soap_new_req_ns1__ZplmMccPositionT(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__ZplmMccPositionT(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__ZplmMccPositionT(soap*, ns1__ZplmMccPositionT*) deserialize from a stream
/// - int soap_write_ns1__ZplmMccPositionT(soap, ns1__ZplmMccPositionT*) serialize to a stream
class ns1__ZplmMccPositionT
{ public:
/// Vector of ns1__ZplmMccPosition* with length 0..unbounded
    std::vector<ns1__ZplmMccPosition*  > item                           0;
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "urn:sap-com:document:sap:soap:functions:mc-style":Bapiret2T is a complexType.
/// class ns1__Bapiret2T operations:
/// - soap_new_ns1__Bapiret2T(soap*) allocate
/// - soap_new_ns1__Bapiret2T(soap*, int num) allocate array
/// - soap_new_req_ns1__Bapiret2T(soap*, ...) allocate, set required members
/// - soap_new_set_ns1__Bapiret2T(soap*, ...) allocate, set all public members
/// - int soap_read_ns1__Bapiret2T(soap*, ns1__Bapiret2T*) deserialize from a stream
/// - int soap_write_ns1__Bapiret2T(soap, ns1__Bapiret2T*) serialize to a stream
class ns1__Bapiret2T
{ public:
/// Vector of ns1__Bapiret2* with length 0..unbounded
    std::vector<ns1__Bapiret2*         > item                           0;
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "urn:sap-com:document:sap:soap:functions:mc-style":ZPlmMccCadCreateMatpl

/// "urn:sap-com:document:sap:soap:functions:mc-style":ZPlmMccCadCreateMatpl is a complexType.
/// class _ns1__ZPlmMccCadCreateMatpl operations:
/// - soap_new__ns1__ZPlmMccCadCreateMatpl(soap*) allocate
/// - soap_new__ns1__ZPlmMccCadCreateMatpl(soap*, int num) allocate array
/// - soap_new_req__ns1__ZPlmMccCadCreateMatpl(soap*, ...) allocate, set required members
/// - soap_new_set__ns1__ZPlmMccCadCreateMatpl(soap*, ...) allocate, set all public members
/// - int soap_read__ns1__ZPlmMccCadCreateMatpl(soap*, _ns1__ZPlmMccCadCreateMatpl*) deserialize from a stream
/// - int soap_write__ns1__ZPlmMccCadCreateMatpl(soap, _ns1__ZPlmMccCadCreateMatpl*) serialize to a stream
class _ns1__ZPlmMccCadCreateMatpl
{ public:
/// Element IdExpAdd of type "urn:sap-com:document:sap:rfc:functions":char1.
    ns2__char1*                          IdExpAdd                       0;	///< Optional element.
/// Element IdNodedest of type "urn:sap-com:document:sap:rfc:functions":char40.
    ns2__char40                          IdNodedest                     1;	///< Required element.
/// Element ItNodeHierarchie of type "urn:sap-com:document:sap:soap:functions:mc-style":ZplmMccNodeHierarchyT.
    ns1__ZplmMccNodeHierarchyT*          ItNodeHierarchie               1;	///< Required element.
/// Element ItPosition of type "urn:sap-com:document:sap:soap:functions:mc-style":ZplmMccPositionT.
    ns1__ZplmMccPositionT*               ItPosition                     1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Top-level root element "urn:sap-com:document:sap:soap:functions:mc-style":ZPlmMccCadCreateMatplResponse

/// "urn:sap-com:document:sap:soap:functions:mc-style":ZPlmMccCadCreateMatplResponse is a complexType.
/// class _ns1__ZPlmMccCadCreateMatplResponse operations:
/// - soap_new__ns1__ZPlmMccCadCreateMatplResponse(soap*) allocate
/// - soap_new__ns1__ZPlmMccCadCreateMatplResponse(soap*, int num) allocate array
/// - soap_new_req__ns1__ZPlmMccCadCreateMatplResponse(soap*, ...) allocate, set required members
/// - soap_new_set__ns1__ZPlmMccCadCreateMatplResponse(soap*, ...) allocate, set all public members
/// - int soap_read__ns1__ZPlmMccCadCreateMatplResponse(soap*, _ns1__ZPlmMccCadCreateMatplResponse*) deserialize from a stream
/// - int soap_write__ns1__ZPlmMccCadCreateMatplResponse(soap, _ns1__ZPlmMccCadCreateMatplResponse*) serialize to a stream
class _ns1__ZPlmMccCadCreateMatplResponse
{ public:
/// Element EsReturn of type "urn:sap-com:document:sap:soap:functions:mc-style":Bapiret2.
    ns1__Bapiret2*                       EsReturn                       1;	///< Required element.
/// Element EtAddPosition of type "urn:sap-com:document:sap:soap:functions:mc-style":ZplmMccPositionT.
    ns1__ZplmMccPositionT*               EtAddPosition                  1;	///< Required element.
/// Element EtPosition of type "urn:sap-com:document:sap:soap:functions:mc-style":ZplmMccPositionT.
    ns1__ZplmMccPositionT*               EtPosition                     1;	///< Required element.
/// Element EtReturn of type "urn:sap-com:document:sap:soap:functions:mc-style":Bapiret2T.
    ns1__Bapiret2T*                      EtReturn                       1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   urn:sap-com:document:sap:rfc:functions                                   *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   urn:sap-com:document:sap:rfc:functions                                   *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   urn:sap-com:document:sap:soap:functions:mc-style                         *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   urn:sap-com:document:sap:soap:functions:mc-style                         *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/

// This service supports SOAP 1.2 namespaces:
#import "soap12.h"

//gsoap ns1  service name:	binding 
//gsoap ns1  service type:	ZPLM_USCOREMCC_USCORECAD_USCORECREATE_USCOREMATPL 
//gsoap ns1  service port:	http://MINA9004.minimaxsap.int:8000/sap/bc/srt/rfc/sap/zplm_mcc_cad_create_matpl/015/service/binding 
//gsoap ns1  service namespace:	urn:sap-com:document:sap:soap:functions:mc-style 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_documentation Documentation
<sidl:sidl xmlns:sidl="http://www.sap.com/2007/03/sidl"/>

@section Service_bindings Service Bindings

  - @ref binding

@section Service_more More Information

  - @ref page_notes "Usage Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page binding Binding "binding"

@section binding_operations Operations of Binding  "binding"

  - @ref __ns1__ZPlmMccCadCreateMatpl

  - @ref __ns1__ZPlmMccCadCreateMatpl_

@section binding_ports Endpoints of Binding  "binding"

  - http://MINA9004.minimaxsap.int:8000/sap/bc/srt/rfc/sap/zplm_mcc_cad_create_matpl/015/service/binding

@section binding_policy Policy of Binding  "binding"

See Section @ref binding_policy_enablers

  - WS-Policy applicable to the service endpoint ports:
	- Exactly one of the following:
		- All of the following:
			- [7.3] Transport Binding requirements:
				- [7.1] Security Binding Algorithm Suite requirements:
					- Basic128Rsa15
				- [7.2] WS-Security Header Layout requirements:
					- WS-Security headers 'declare before use' required (gSOAP default)
				- Transport requirements:
					- [5.4.10] HTTPS required:
						- HTTP/S Basic Authentication required:
	@code
	soap->userid = "<userid>"; soap->passwd = "<passwd>";
soap_call_ns__method(...)
	@endcode
			- [7.3] Transport Binding requirements:
				- [7.1] Security Binding Algorithm Suite requirements:
					- Basic128Rsa15
				- [7.2] WS-Security Header Layout requirements:
					- WS-Security headers 'declare before use' required (gSOAP default)
				- Transport requirements:
					- [5.4.10] HTTPS required:
						- Other policy requirements:
	@verbatim
<sapsp:HTTPSSO2/>
	@endverbatim
	- WS-Addressing is used
	- Other policy requirements:
	@verbatim
<saptrnbnd:OptimizedXMLTransfer uri="http://xml.sap.com/2006/11/esi/esp/binxml"
xmlns:saptrnbnd="http://www.sap.com/webas/710/soap/features/transportbinding/"
wsp:Optional="true"/>
	@endverbatim
	- Other policy requirements:
	@verbatim
<saptrnbnd:OptimizedMimeSerialization xmlns:saptrnbnd="http://schemas.xmlsoap.org/ws/2004/09/policy/optimizedmimeserialization"
wsp:Optional="true"/>
	@endverbatim

Note: use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   binding                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__ZPlmMccCadCreateMatpl                                             *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__ZPlmMccCadCreateMatpl" of service binding "binding"

/**

Operation details:

  - WS-Policy applicable to the operation:
	- Other policy requirements:
	@verbatim
<sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
	@endverbatim
	- Other policy requirements:
	@verbatim
<sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
	@endverbatim
	- Other policy requirements:
	@verbatim
<saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
	@endverbatim
	- Other policy requirements:
	@verbatim
<saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
	@endverbatim

  - SOAP document/literal style messaging

  - Action: "urn:sap-com:document:sap:soap:functions:mc-style:ZPLM_MCC_CAD_CREATE_MATPL:ZPlmMccCadCreateMatplRequest"

  - Addressing input action: "urn:sap-com:document:sap:soap:functions:mc-style:ZPLM_MCC_CAD_CREATE_MATPL:ZPlmMccCadCreateMatplRequest"

  - Addressing output action: "urn:sap-com:document:sap:soap:functions:mc-style:ZPLM_MCC_CAD_CREATE_MATPL:ZPlmMccCadCreateMatplRequestResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__ZPlmMccCadCreateMatpl(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__ZPlmMccCadCreateMatpl*        ns1__ZPlmMccCadCreateMatpl,
    // output parameters:
    _ns1__ZPlmMccCadCreateMatplResponse* ns1__ZPlmMccCadCreateMatplResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__ZPlmMccCadCreateMatpl(
    struct soap *soap,
    // input parameters:
    _ns1__ZPlmMccCadCreateMatpl*        ns1__ZPlmMccCadCreateMatpl,
    // output parameters:
    _ns1__ZPlmMccCadCreateMatplResponse* ns1__ZPlmMccCadCreateMatplResponse
  );
@endcode

C++ proxy class (defined in soapbindingProxy.h):
@code
  class bindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapbindingService.h):
@code
  class bindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	ZPlmMccCadCreateMatpl SOAP
//gsoap ns1  service method-style:	ZPlmMccCadCreateMatpl document
//gsoap ns1  service method-encoding:	ZPlmMccCadCreateMatpl literal
//gsoap ns1  service method-input-action:	ZPlmMccCadCreateMatpl urn:sap-com:document:sap:soap:functions:mc-style:ZPLM_MCC_CAD_CREATE_MATPL:ZPlmMccCadCreateMatplRequest
//gsoap ns1  service method-output-action:	ZPlmMccCadCreateMatpl urn:sap-com:document:sap:soap:functions:mc-style:ZPLM_MCC_CAD_CREATE_MATPL:ZPlmMccCadCreateMatplRequestResponse
int __ns1__ZPlmMccCadCreateMatpl(
    _ns1__ZPlmMccCadCreateMatpl*        ns1__ZPlmMccCadCreateMatpl,	///< Input parameter
    _ns1__ZPlmMccCadCreateMatplResponse* ns1__ZPlmMccCadCreateMatplResponse	///< Output parameter
);

/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__ZPlmMccCadCreateMatpl_                                            *
 *                                                                            *
\******************************************************************************/


/// Operation "__ns1__ZPlmMccCadCreateMatpl_" of service binding "binding"

/**

Operation details:

  - WS-Policy applicable to the operation:
	- Other policy requirements:
	@verbatim
<sapcomhnd:enableCommit xmlns:sapcomhnd="http://www.sap.com/NW05/soap/features/commit/">false</sapcomhnd:enableCommit>
	@endverbatim
	- Other policy requirements:
	@verbatim
<sapblock:enableBlocking xmlns:sapblock="http://www.sap.com/NW05/soap/features/blocking/">true</sapblock:enableBlocking>
	@endverbatim
	- Other policy requirements:
	@verbatim
<saptrhnw05:required xmlns:saptrhnw05="http://www.sap.com/NW05/soap/features/transaction/">no</saptrhnw05:required>
	@endverbatim
	- Other policy requirements:
	@verbatim
<saprmnw05:enableWSRM xmlns:saprmnw05="http://www.sap.com/NW05/soap/features/wsrm/">false</saprmnw05:enableWSRM>
	@endverbatim

  - SOAP document/literal style messaging

  - Action: "urn:sap-com:document:sap:soap:functions:mc-style:ZPLM_MCC_CAD_CREATE_MATPL:ZPlmMccCadCreateMatplRequest"

  - Addressing input action: "urn:sap-com:document:sap:soap:functions:mc-style:ZPLM_MCC_CAD_CREATE_MATPL:ZPlmMccCadCreateMatplRequest"

  - Addressing output action: "urn:sap-com:document:sap:soap:functions:mc-style:ZPLM_MCC_CAD_CREATE_MATPL:ZPlmMccCadCreateMatplRequestResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__ZPlmMccCadCreateMatpl_(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    _ns1__ZPlmMccCadCreateMatpl*        ns1__ZPlmMccCadCreateMatpl,
    // output parameters:
    _ns1__ZPlmMccCadCreateMatplResponse* ns1__ZPlmMccCadCreateMatplResponse
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__ZPlmMccCadCreateMatpl_(
    struct soap *soap,
    // input parameters:
    _ns1__ZPlmMccCadCreateMatpl*        ns1__ZPlmMccCadCreateMatpl,
    // output parameters:
    _ns1__ZPlmMccCadCreateMatplResponse* ns1__ZPlmMccCadCreateMatplResponse
  );
@endcode

C++ proxy class (defined in soapbindingProxy.h):
@code
  class bindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use proxy classes;

C++ service class (defined in soapbindingService.h):
@code
  class bindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate greatly improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	ZPlmMccCadCreateMatpl_ SOAP
//gsoap ns1  service method-style:	ZPlmMccCadCreateMatpl_ document
//gsoap ns1  service method-encoding:	ZPlmMccCadCreateMatpl_ literal
//gsoap ns1  service method-input-action:	ZPlmMccCadCreateMatpl_ urn:sap-com:document:sap:soap:functions:mc-style:ZPLM_MCC_CAD_CREATE_MATPL:ZPlmMccCadCreateMatplRequest
//gsoap ns1  service method-output-action:	ZPlmMccCadCreateMatpl_ urn:sap-com:document:sap:soap:functions:mc-style:ZPLM_MCC_CAD_CREATE_MATPL:ZPlmMccCadCreateMatplRequestResponse
int __ns1__ZPlmMccCadCreateMatpl_(
    _ns1__ZPlmMccCadCreateMatpl*        ns1__ZPlmMccCadCreateMatpl,	///< Input parameter
    _ns1__ZPlmMccCadCreateMatplResponse* ns1__ZPlmMccCadCreateMatplResponse	///< Output parameter
);

/**

@page binding Binding "binding"

@section binding_policy_enablers Policy Enablers of Binding  "binding"

Based on policies, this service imports wsse.h wsa5.h

  - WS-Policy reminders and enablers:
    - WS-Addressing 1.0 (2005/08, accepts 2004/08):
	@code
	#import "wsa5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-Addressing (2004/08):
	@code
	#import "wsa.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsaapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	// See the user guide gsoap/doc/wsa/html/index.html
	@endcode
    - WS-ReliableMessaging 1.0:
	@code
	#import "wsrm5.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-ReliableMessaging 1.1:
	@code
	#import "wsrm.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsrmapi.h"
	soap_register_plugin(soap, soap_wsa); // register the wsa plugin in your code
	soap_register_plugin(soap, soap_wsrm); // register the wsrm plugin in your code
	// See the user guide gsoap/doc/wsrm/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.0 (accepts 1.1):
	@code
	#import "wsse.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - WS-Security (SOAP Message Security) 1.1 (accepts 1.0):
	@code
	#import "wsse11.h" // to be added to this header file for the soapcpp2 build step
	@endcode
	@code
	#include "plugin/wsseapi.h"
	soap_register_plugin(soap, soap_wsse); // register the wsse plugin in your code
	// See the user guide gsoap/doc/wsse/html/index.html
	@endcode
    - HTTP Digest Authentication:
	@code
	#include "plugin/httpda.h"
	soap_register_plugin(soap, soap_http_da); // register the HTTP DA plugin in your code
	// See the user guide gsoap/doc/httpda/html/index.html
	@endcode
*/

#import "wsse.h"
#import "wsa5.h"

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

Data can be read in XML and deserialized from:
  - a file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->is = ...
  - a buffer, using the soap->frecv() callback

Data can be serialized in XML and written to:
  - a file descriptor, using soap->sendfd = fd
  - a socket, using soap->socket = ...
  - a C++ stream, using soap->os = ...
  - a buffer, using the soap->fsend() callback

The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


@section ns2 Top-level root elements of schema "urn:sap-com:document:sap:rfc:functions"

@section ns1 Top-level root elements of schema "urn:sap-com:document:sap:soap:functions:mc-style"

  - <ns1:ZPlmMccCadCreateMatpl> @ref _ns1__ZPlmMccCadCreateMatpl
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__ZPlmMccCadCreateMatpl(struct soap*, _ns1__ZPlmMccCadCreateMatpl*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__ZPlmMccCadCreateMatpl(struct soap*, _ns1__ZPlmMccCadCreateMatpl*);
    @endcode

  - <ns1:ZPlmMccCadCreateMatplResponse> @ref _ns1__ZPlmMccCadCreateMatplResponse
    @code
    // Reader (returns SOAP_OK on success):
    soap_read__ns1__ZPlmMccCadCreateMatplResponse(struct soap*, _ns1__ZPlmMccCadCreateMatplResponse*);
    // Writer (returns SOAP_OK on success):
    soap_write__ns1__ZPlmMccCadCreateMatplResponse(struct soap*, _ns1__ZPlmMccCadCreateMatplResponse*);
    @endcode

*/

/* End of matt.h */
