/* soapbindingProxy.cpp
   Generated by gSOAP 2.8.17r from matt.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include <stdafx.h>
#include "soapbindingProxy.h"

bindingProxy::bindingProxy()
{	bindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

bindingProxy::bindingProxy(const struct soap &_soap) : soap(_soap)
{ }

bindingProxy::bindingProxy(const char *url)
{	bindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

bindingProxy::bindingProxy(soap_mode iomode)
{	bindingProxy_init(iomode, iomode);
}

bindingProxy::bindingProxy(const char *url, soap_mode iomode)
{	bindingProxy_init(iomode, iomode);
	soap_endpoint = url;
}

bindingProxy::bindingProxy(soap_mode imode, soap_mode omode)
{	bindingProxy_init(imode, omode);
}

bindingProxy::~bindingProxy()
{ }

void bindingProxy::bindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	soap_endpoint = NULL;

	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
//	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
//	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
//	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
//	{"ns2", "urn:sap-com:document:sap:rfc:functions", NULL, NULL},
	{"ns1", "urn:sap-com:document:sap:soap:functions:mc-style", NULL, NULL},
//	{"c14n", "http://www.w3.org/2001/10/xml-exc-c14n#", NULL, NULL},
//	{"wsu", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", NULL, NULL},
//	{"xenc", "http://www.w3.org/2001/04/xmlenc#", NULL, NULL},
//	{"wsc", "http://schemas.xmlsoap.org/ws/2005/02/sc", NULL, NULL},
//	{"ds", "http://www.w3.org/2000/09/xmldsig#", NULL, NULL},
//	{"wsse", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd", "http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd", NULL},
//	{"chan", "http://schemas.microsoft.com/ws/2005/02/duplex", NULL, NULL},
//	{"wsa5", "http://www.w3.org/2005/08/addressing", "http://schemas.xmlsoap.org/ws/2004/08/addressing", NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this, namespaces);
}

void bindingProxy::destroy()
{	soap_destroy(this);
	soap_end(this);
}

void bindingProxy::reset()
{	destroy();
	soap_done(this);
	soap_initialize(this);
	bindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void bindingProxy::soap_noheader()
{	this->header = NULL;
}

void bindingProxy::soap_header(struct _wsse__Security *wsse__Security, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance)
{	::soap_header(this);
	this->header->wsse__Security = wsse__Security;
	this->header->wsa5__MessageID = wsa5__MessageID;
	this->header->wsa5__RelatesTo = wsa5__RelatesTo;
	this->header->wsa5__From = wsa5__From;
	this->header->wsa5__ReplyTo = wsa5__ReplyTo;
	this->header->wsa5__FaultTo = wsa5__FaultTo;
	this->header->wsa5__To = wsa5__To;
	this->header->wsa5__Action = wsa5__Action;
	this->header->chan__ChannelInstance = chan__ChannelInstance;
}

const SOAP_ENV__Header *bindingProxy::soap_header()
{	return this->header;
}

const SOAP_ENV__Fault *bindingProxy::soap_fault()
{	return this->fault;
}

const char *bindingProxy::soap_fault_string()
{	return *soap_faultstring(this);
}

const char *bindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this);
}

int bindingProxy::soap_close_socket()
{	return soap_closesock(this);
}

int bindingProxy::soap_force_close_socket()
{	return soap_force_closesock(this);
}

void bindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void bindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}
#endif

char *bindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

int bindingProxy::ZPlmMccCadCreateMatpl(const char *endpoint, const char *soap_action, _ns1__ZPlmMccCadCreateMatpl *ns1__ZPlmMccCadCreateMatpl, _ns1__ZPlmMccCadCreateMatplResponse *ns1__ZPlmMccCadCreateMatplResponse)
{	struct soap *soap = this;
	struct __ns1__ZPlmMccCadCreateMatpl soap_tmp___ns1__ZPlmMccCadCreateMatpl;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://MINA9004:8000/sap/bc/srt/rfc/sap/zplm_mcc_cad_create_matpl/015/service/binding";
	if (soap_action == NULL)
		soap_action = "urn:sap-com:document:sap:soap:functions:mc-style:ZPLM_MCC_CAD_CREATE_MATPL:ZPlmMccCadCreateMatplRequest";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__ZPlmMccCadCreateMatpl.ns1__ZPlmMccCadCreateMatpl = ns1__ZPlmMccCadCreateMatpl;
	soap_serializeheader(soap);
	soap_serialize___ns1__ZPlmMccCadCreateMatpl(soap, &soap_tmp___ns1__ZPlmMccCadCreateMatpl);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ZPlmMccCadCreateMatpl(soap, &soap_tmp___ns1__ZPlmMccCadCreateMatpl, "-ns1:ZPlmMccCadCreateMatpl", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ZPlmMccCadCreateMatpl(soap, &soap_tmp___ns1__ZPlmMccCadCreateMatpl, "-ns1:ZPlmMccCadCreateMatpl", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__ZPlmMccCadCreateMatplResponse)
		return soap_closesock(soap);
	ns1__ZPlmMccCadCreateMatplResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__ZPlmMccCadCreateMatplResponse->soap_get(soap, "ns1:ZPlmMccCadCreateMatplResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int bindingProxy::ZPlmMccCadCreateMatpl_(const char *endpoint, const char *soap_action, _ns1__ZPlmMccCadCreateMatpl *ns1__ZPlmMccCadCreateMatpl, _ns1__ZPlmMccCadCreateMatplResponse *ns1__ZPlmMccCadCreateMatplResponse)
{	struct soap *soap = this;
	struct __ns1__ZPlmMccCadCreateMatpl_ soap_tmp___ns1__ZPlmMccCadCreateMatpl_;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://MINA9004.minimaxsap.int:8000/sap/bc/srt/rfc/sap/zplm_mcc_cad_create_matpl/015/service/binding";
	if (soap_action == NULL)
		soap_action = "urn:sap-com:document:sap:soap:functions:mc-style:ZPLM_MCC_CAD_CREATE_MATPL:ZPlmMccCadCreateMatplRequest";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__ZPlmMccCadCreateMatpl_.ns1__ZPlmMccCadCreateMatpl = ns1__ZPlmMccCadCreateMatpl;
	soap_serializeheader(soap);
	soap_serialize___ns1__ZPlmMccCadCreateMatpl_(soap, &soap_tmp___ns1__ZPlmMccCadCreateMatpl_);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ZPlmMccCadCreateMatpl_(soap, &soap_tmp___ns1__ZPlmMccCadCreateMatpl_, "-ns1:ZPlmMccCadCreateMatpl", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ZPlmMccCadCreateMatpl_(soap, &soap_tmp___ns1__ZPlmMccCadCreateMatpl_, "-ns1:ZPlmMccCadCreateMatpl", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__ZPlmMccCadCreateMatplResponse)
		return soap_closesock(soap);
	ns1__ZPlmMccCadCreateMatplResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__ZPlmMccCadCreateMatplResponse->soap_get(soap, "ns1:ZPlmMccCadCreateMatplResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
