/* soapbindingProxy.h
   Generated by gSOAP 2.8.17r from matt.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapbindingProxy_H
#define soapbindingProxy_H
#include "soapH.h"

class SOAP_CMAC bindingProxy : public soap
{ public:
	/// Endpoint URL of service 'bindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	bindingProxy();
	/// Construct from another engine state
	bindingProxy(const struct soap&);
	/// Constructor with endpoint URL
	bindingProxy(const char *url);
	/// Constructor with engine input+output mode control
	bindingProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	bindingProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	bindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~bindingProxy();
	/// Initializer used by constructors
	virtual	void bindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Put SOAP Header in message
	virtual	void soap_header(struct _wsse__Security *wsse__Security, char *wsa5__MessageID, struct wsa5__RelatesToType *wsa5__RelatesTo, struct wsa5__EndpointReferenceType *wsa5__From, struct wsa5__EndpointReferenceType *wsa5__ReplyTo, struct wsa5__EndpointReferenceType *wsa5__FaultTo, char *wsa5__To, char *wsa5__Action, struct chan__ChannelInstanceType *chan__ChannelInstance);
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'ZPlmMccCadCreateMatpl' (returns error code or SOAP_OK)
	virtual	int ZPlmMccCadCreateMatpl(_ns1__ZPlmMccCadCreateMatpl *ns1__ZPlmMccCadCreateMatpl, _ns1__ZPlmMccCadCreateMatplResponse *ns1__ZPlmMccCadCreateMatplResponse) { return this->ZPlmMccCadCreateMatpl(NULL, NULL, ns1__ZPlmMccCadCreateMatpl, ns1__ZPlmMccCadCreateMatplResponse); }
	virtual	int ZPlmMccCadCreateMatpl(const char *endpoint, const char *soap_action, _ns1__ZPlmMccCadCreateMatpl *ns1__ZPlmMccCadCreateMatpl, _ns1__ZPlmMccCadCreateMatplResponse *ns1__ZPlmMccCadCreateMatplResponse);

	/// Web service operation 'ZPlmMccCadCreateMatpl' (returns error code or SOAP_OK)
	virtual	int ZPlmMccCadCreateMatpl_(_ns1__ZPlmMccCadCreateMatpl *ns1__ZPlmMccCadCreateMatpl, _ns1__ZPlmMccCadCreateMatplResponse *ns1__ZPlmMccCadCreateMatplResponse) { return this->ZPlmMccCadCreateMatpl_(NULL, NULL, ns1__ZPlmMccCadCreateMatpl, ns1__ZPlmMccCadCreateMatplResponse); }
	virtual	int ZPlmMccCadCreateMatpl_(const char *endpoint, const char *soap_action, _ns1__ZPlmMccCadCreateMatpl *ns1__ZPlmMccCadCreateMatpl, _ns1__ZPlmMccCadCreateMatplResponse *ns1__ZPlmMccCadCreateMatplResponse);
};
#endif
