# ----------------------------------------------------------
# app project generated by QMsNet (save function)
# ----------------------------------------------------------
TEMPLATE  = app
LANGUAGE  = C++

TRANSLATIONS    = tt2_fr.ts \
                  tt2_enu.ts
                  
CONFIG	 += qt warn_on

OBJECTS_DIR = tmp\obj
MOC_DIR     = tmp\moc

HEADERS   =  \
	.\spanxdiff.h
SOURCES   =  \
	main.cpp \
	.\spanxdiff.cpp
